from ...NXOpen import *
from ..CollaborationApplication import *

import typing
import enum

class SubscriptionMgr(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def UpdateSubscription(self, displayNames: str) -> None:
        ...
    def FreeResource(self) -> None:
        ...
    FollowPartsOnLoadFlag: bool


class SessionManager(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def GetSubscriptionManager(self) -> CollaborationApplication.SubscriptionMgr:
        ...
    def SetMockCollaborationEvent(self, userName: str, cliSpecNameFromPlmObject: str, eventType: int, cliSpecEventBodyString: str) -> None:
        ...
    def DeleteCards(self, cardIDs: int) -> None:
        ...
    def PrintCardInformation(self) -> None:
        ...
    def PrintSubscriptionInformation(self) -> None:
        ...
    def PrintSubscriptionCount(self) -> None:
        ...
    def Tag(self) -> Tag: ...



class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


