from ...NXOpen import *
from ..Options import *

import typing
import enum

class OptionType(enum.Enum):
    Int = 0
    Real = 1
    String = 2
    StringList = 3
    Logical = 4
    Utf8string = 5
    Utf8stringList = 6
    ReorderSelList = 7


class OptionsScope(enum.Enum):
    Part = 0
    Session = 1


class OptionsManager(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def GetIntValue(self, name: str) -> int:
        ...
    def GetRealValue(self, name: str) -> float:
        ...
    def GetStringValue(self, name: str) -> str:
        ...
    def GetUtf8stringValue(self, name: str) -> str:
        ...
    def GetStringListValue(self, name: str) -> str:
        ...
    def GetReorderSelectableStringListValue(self, name: str, selection: bool) -> str:
        ...
    def GetLogicalValue(self, name: str) -> bool:
        ...
    def GetIntValue(self, name: str, level: Options.LevelType) -> int:
        ...
    def GetRealValue(self, name: str, level: Options.LevelType) -> float:
        ...
    def GetStringValue(self, name: str, level: Options.LevelType) -> str:
        ...
    def GetUtf8stringValue(self, name: str, level: Options.LevelType) -> str:
        ...
    def GetStringListValue(self, name: str, level: Options.LevelType) -> str:
        ...
    def GetReorderSelectableStringListValue(self, name: str, level: Options.LevelType, selection: bool) -> str:
        ...
    def GetLogicalValue(self, name: str, level: Options.LevelType) -> bool:
        ...
    def NewOptionsChangeList(self, level: Options.LevelType, lockedByDefault: Options.LevelLockedByDefault) -> Options.ChangeList:
        ...
    def NewOptionsDraftingStandardChangeList(self, level: Options.LevelType, filename: str) -> Options.DraftingStandardChangeList:
        ...
    def GetAllOptions(self) -> str:
        ...
    def IsValueLocked(self, name: str, level: Options.LevelType) -> bool:
        ...
    def IsValueSet(self, name: str, level: Options.LevelType) -> bool:
        ...
    def GetUserComment(self, name: str, level: Options.LevelType) -> str:
        ...
    def GetOptionType(self, name: str) -> Options.OptionType:
        ...
    def IsLevelLockedByDefault(self, level: Options.LevelType) -> bool:
        ...
    def GetScope(self, name: str) -> Options.OptionsScope:
        ...
    def Tag(self) -> Tag: ...



class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class LevelType(enum.Enum):
    Shipped = 0
    Package = 1
    Site = 2
    Group = 3
    User = 4


class LevelLockedByDefault(enum.Enum):
    False = 0
    True = 1


class DraftingStandardChangeList(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def SetValue(self, name: str, value: int) -> None:
        ...
    def SetValue(self, name: str, value: float) -> None:
        ...
    def SetValue(self, name: str, value: str) -> None:
        ...
    def SetUtf8Value(self, name: str, value: str) -> None:
        ...
    def SetValue(self, name: str, value: str) -> None:
        ...
    def SetValueOrder(self, name: str, value: str) -> None:
        ...
    def SetValueSelection(self, name: str, selection: bool, value: str) -> None:
        ...
    def SetValue(self, name: str, value: bool) -> None:
        ...
    def SetUserComment(self, name: str, comment: str) -> None:
        ...
    def LockValue(self, name: str) -> None:
        ...
    def UnlockValue(self, name: str) -> None:
        ...
    def Save(self) -> None:
        ...
    def FreeResource(self) -> None:
        ...
    def Load(self) -> None:
        ...
    CurrentLevel: Options.LevelType


class ChangeList(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def SetValue(self, name: str, value: int) -> None:
        ...
    def SetValue(self, name: str, value: float) -> None:
        ...
    def SetValue(self, name: str, value: str) -> None:
        ...
    def SetUtf8Value(self, name: str, value: str) -> None:
        ...
    def SetUtf8Value(self, name: str, value: str) -> None:
        ...
    def SetValue(self, name: str, value: str) -> None:
        ...
    def SetValueOrder(self, name: str, value: str) -> None:
        ...
    def SetValueSelection(self, name: str, selection: bool, value: str) -> None:
        ...
    def SetValue(self, name: str, value: bool) -> None:
        ...
    def SetUserComment(self, name: str, comment: str) -> None:
        ...
    def DeleteValue(self, name: str) -> None:
        ...
    def LockValue(self, name: str) -> None:
        ...
    def UnlockValue(self, name: str) -> None:
        ...
    def Save(self) -> None:
        ...
    def FreeResource(self) -> None:
        ...
    CurrentLevel: Options.LevelType
    LockedByDefault: Options.LevelLockedByDefault


