from . import SaveManagement
from ...NXOpen import *
from ..PDM import *

import typing
import enum

class WebAppSession(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def CreateCustomWebAppMenuHandler(self) -> PDM.CustomWebAppMenuHandler:
        ...
    def Open(self, databaseObjects: typing.List[PDM.DatabaseObject]) -> None:
        ...
    def ShowSummary(self, uid: str, objType: str, classId: str) -> None:
        ...
    def OpenProductContext(self, uid: str, loadStatus: PartLoadStatus) -> BasePart:
        ...
    def ShapeSearch(self, uid: str, part: BasePart, classId: str) -> None:
        ...
    def Tag(self) -> Tag: ...



class VariantRulesConfigurationBuilder(Builder):
    def __init__(self) -> None: ...
    def GetVariantRulesForProductAssembly(self, contextId: str, revId: str) -> str:
        ...
    def GetVariantRulesSelectedForConfiguration(self, contextIds: str, variantRules: str) -> None:
        ...
    def AddVariantRulesToConfigure(self, contextIds: str, variantRules: str) -> None:
        ...


class VariantConfigurationBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def AskAvailableVariantRules(self, contextId: str, revId: str) -> str:
        ...
    def GetVariantRuleTableInformation(self, contextIds: str, variantRules: str) -> None:
        ...
    def RemoveVariantRule(self, contextId: str, variantRule: str) -> None:
        ...
    def AddMultipleVariantRules(self, contextIds: str, variantRules: str) -> None:
        ...
    def Validate(self) -> bool:
        ...


class TracelinkQuery(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...
    def GetTracelinkRelationsXml(self) -> str:
        ...


class TcinUtils(Utilities.NXRemotableObject):
    def __init__(self, owner: PDM.PdmSession) -> None: ...
    def ConvertLegacyDesignControlElements(self, designControlElements: typing.List[Assemblies.Component], legacyDCEIds: str, newDesignFeatureIds: str) -> None:
        ...
    def CreateVariantExpressions(self, parts: typing.List[Part]) -> None:
        """[Obsolete("Deprecated in NX1872.0.0.  Use NXOpen.PDM.TcinUtils.CreatePCAExpressions instead")"""
        ...
    def CreatePCAExpressions(self, parts: typing.List[Part]) -> None:
        ...
    def Tag(self) -> Tag: ...



class SoaQuery(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...
    def AddFieldDescription(self, searchVar: PDM.PdmSearch, type: PDM.PdmSoaqueryNxmgrfielddatatype, name: str, attrName: str, defaultValue: str, logicalOperation: str, mathOperation: str, lov: PDM.ListOfValues) -> None:
        """[Obsolete("Deprecated in NX8.0.0.  It's not needed in any context of search based on queries.")"""
        ...


class SmartSaveObject(NXObject):
    def __init__(self) -> None: ...
    def GetModificationReason(self) -> str:
        ...
    def IsFrozenByStatus(self) -> bool:
        ...
    def IsModifiable(self) -> bool:
        ...
    def HasAddContentPrivilege(self) -> bool:
        ...
    def HasRemoveContentPrivilege(self) -> bool:
        ...
    def IsNonMaster(self) -> bool:
        ...
    def IsMajorRevisable(self) -> bool:
        ...
    def IsReleased(self) -> bool:
        ...
    def IsCheckedOutByAnotherUser(self) -> bool:
        ...
    def IsExplicitCheckOutNeeded(self) -> bool:
        ...
    def IsDisplayedOnTheSaveDialog(self) -> bool:
        ...
    def SetAsDisplayedOnTheSaveDialog(self, markDisplayedOnDialog: bool) -> None:
        ...
    def GetCurrentOperationType(self) -> PDM.SmartSaveObject.OperationType:
        ...
    def SetCurrentOperationType(self, newOperationType: PDM.SmartSaveObject.OperationType) -> None:
        ...
    def GetValidOperationTypes(self) -> typing.List[PDM.SmartSaveObject.OperationType]:
        ...
    def GetTeamcenterObjectType(self) -> str:
        ...
    def SetValidOperationTypes(self, newValidOperationTypes: typing.List[PDM.SmartSaveObject.OperationType]) -> None:
        ...
    def GetEffectivityFormula(self) -> str:
        ...
    def SetEffectivityFormula(self, effectivityFormula: str, effectivityDisplayString: str) -> None:
        ...


    class OperationType(enum.Enum):
        None = -1
        Create = 0
        Revise = 1
        SaveAs = 2
        Save = 3
        Delete = 4
    

class SmartSaveContext(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...
    def SetWorkObjectToRootObjectMap(self, workObjects: typing.List[TaggedObject], rootObjects: typing.List[TaggedObject]) -> None:
        ...
    def GetWorkObjectToRootObjectMap(self, workObjects: typing.List[TaggedObject], rootObjects: typing.List[TaggedObject]) -> None:
        ...
    def GetSaveType(self) -> PDM.SmartSaveBuilder.SaveType:
        ...


class SmartSaveBuilder(Builder):
    def __init__(self) -> None: ...
    def GetSmartSaveObjects(self, smartSaveObjects: typing.List[PDM.SmartSaveObject]) -> None:
        ...
    def OnOperationTypeChanged(self, smartSaveObjects: typing.List[PDM.SmartSaveObject], operationType: AttributePropertiesBuilder.OperationType) -> None:
        ...
    def GetOperationFailures(self) -> ErrorList:
        ...
    def ClearValidationFailures(self) -> None:
        ...
    def UpdateSmartSaveObjectsOnBuilder(self) -> None:
        ...
    def CanPerformDefaultSave(self) -> bool:
        ...
    def ValidateSmartSaveObjects(self) -> None:
        ...
    def CreateSpecificationsForSmartSaveObjects(self, smartSaveObjects: typing.List[PDM.SmartSaveObject]) -> None:
        ...
    def GetErrorMessageHandler(self, refresh: bool) -> PDM.ErrorMessageHandler:
        ...
    def AssignRemoveProjects(self, smartSaveObjects: typing.List[PDM.SmartSaveObject], projectNames: str, assignmentStates: typing.List[Session.ProjectAssignmentState]) -> None:
        ...
    def GetAssociatedChangeNoticeNames(self, smartSaveObjects: typing.List[PDM.SmartSaveObject]) -> str:
        ...
    def GetAlternateIDManager(self, logicalObject: PDM.LogicalObject) -> PDM.AlternateIdManager:
        ...
    def AutoAssignAttributes(self, objects: typing.List[NXObject]) -> ErrorList:
        ...
    def AutoAssignAttributesWithNamingPattern(self, objects: typing.List[NXObject], properties: typing.List[NXObject]) -> ErrorList:
        ...
    def CreateAttributeTitleToNamingPatternMap(self, attributeTitles: str, titlePatterns: str) -> NXObject:
        ...
    DebugDumpEnabled: bool
    UseNewSortForDebug: bool


    class SaveType(enum.Enum):
        Save = 0
        SaveAll = 1
        SavePreciseAssembly = 2
        SaveWorkPartOnly = 3
        SaveAndClose = 4
        SaveDesignElements = 5
        ForceSaveAll = 6
    

    class DialogType(enum.Enum):
        Save = 0
        StageModelSaveAs = 1
        DesignSessionSaveAs = 2
    

class SheetRevision(PDM.ConditionalElementRevision):
    def __init__(self) -> None: ...


class SessionSettings(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def GetGroups(self) -> str:
        ...
    def GetRoles(self) -> str:
        ...
    def GetVolumes(self) -> str:
        ...
    def GetLocalVolumes(self) -> str:
        ...
    def GetLocationCodes(self) -> str:
        ...
    def GetProjects(self) -> str:
        ...
    def Apply(self) -> None:
        ...
    def FreeResource(self) -> None:
        ...
    def DumpValidationInfo(self, logFileName: str) -> None:
        ...
    def ApplyAndRefresh(self) -> None:
        ...
    AdministrationBypass: bool
    AdministrationLogging: bool
    ApplicationLogging: bool
    Group: str
    IsAdministrator: bool
    Journaling: bool
    LocalVolume: str
    LocationCode: str
    Project: str
    Role: str
    SecurityLogging: bool
    Volume: str


class SearchResult(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...
    def GetResultObjectNames(self) -> str:
        ...
    def GetResultItemIds(self) -> str:
        """[Obsolete("Deprecated in NX10.0.0.  Use PDM.SearchResult.GetResultMfkIds instead.")"""
        ...
    def GetResultMfkIds(self) -> str:
        ...
    def GetResultObjectTypes(self) -> str:
        ...


class SaveAsReviseObserver(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int:
        ...
    def ToArray(self) -> typing.List[PDM.SaveAsReviseCallbackData]:
        ...
    def __init__(self, owner: PDM.PdmSession) -> None: ...
    def __init__(self) -> None: ...
    def AddPrecopyoperationCallback(self, precopyoperationCb: PDM.SaveAsReviseObserver.PrecopyoperationCb) -> int:
        ...
    def RemovePrecopyoperationCallback(self, id: int) -> None:
        ...
    def AddPostcopyoperationCallback(self, postcopyoperationCb: PDM.SaveAsReviseObserver.PostcopyoperationCb) -> int:
        ...
    def RemovePostcopyoperationCallback(self, id: int) -> None:
        ...
    def Tag(self) -> Tag: ...



    

    

    

    

    

    

class SaveAsReviseCallbackData(TaggedObject):
    def __init__(self) -> None: ...
    def GetSourceObjects(self, sourceObjects: typing.List[TaggedObject]) -> int:
        ...
    def GetCopiedObjects(self, sourceObjects: TaggedObject, copiedObjects: typing.List[TaggedObject]) -> None:
        ...


class RequirementUtils(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def NewTracelinkQuery(self) -> PDM.TracelinkQuery:
        ...
    def CreateTraceLinks(self, requirementItemNumbers: str, requirementRevisions: str, parts: str) -> None:
        ...
    def RemoveTraceLinks(self, requirementItemNumbers: str, requirementRevisions: str, parts: str) -> None:
        ...
    def Tag(self) -> Tag: ...



class PortArtifact(NXObject):
    def __init__(self) -> None: ...


class PersistentSettings(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def GetGroups(self) -> str:
        ...
    def GetVolumes(self) -> str:
        ...
    def Apply(self) -> None:
        ...
    def FreeResource(self) -> None:
        ...
    Group: str
    Volume: str


class PendingComponentsManager(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def GetComponents(self) -> str:
        ...
    def GetComponentPartFileName(self, handle: str) -> str:
        ...
    def ComponentHasPosition(self, handle: str) -> bool:
        ...
    def DeleteComponent(self, handle: str) -> None:
        ...
    def AddComponent(self, handle: str, loadStatus: PartLoadStatus) -> Assemblies.Component:
        ...
    def AddNgcComponent(self, handle: str, loadStatus: PartLoadStatus) -> Assemblies.Component:
        ...
    def FreeResource(self) -> None:
        ...


class PdmSoaqueryNxmgrfielddatatype(enum.Enum):
    Char = 2001
    Date = 2002
    Double = 2003
    Float = 2004
    Int = 2005
    Bool = 2006
    Short = 2007
    String = 2008
    Reference = 2009
    UntypedReference = 2010
    ExternalReference = 2011


class PdmSession(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def GetTcserverSettings(self, connectString: str, discriminator: str) -> None:
        ...
    def GetSsoSettings(self, isSsoEnabled: bool, ssoServerUrl: str, ssoAppID: str) -> None:
        ...
    def SetDefaultFolder(self, defaultFolderSpec: str) -> None:
        ...
    def NewFileManagement(self) -> PDM.FileManagement:
        ...
    def NewCaeFileContainer(self) -> PDM.CAEFileContainer:
        ...
    def CreateCopyOperationBuilder(self, operation: PDM.PartOperationBuilder.OperationType) -> PDM.PartOperationCopyBuilder:
        ...
    def CreateCreateOperationBuilder(self, operation: PDM.PartOperationBuilder.OperationType) -> PDM.PartOperationCreateBuilder:
        ...
    def CreateOperationBuilder(self, operation: PDM.PartOperationBuilder.OperationType) -> PDM.PartOperationBuilder:
        """[Obsolete("Deprecated in NX10.0.0.  Use NXOpen.PDM.PdmSession.CreateCopyOperationBuilder instead")"""
        ...
    def CreateObjectCreateBuilder(self, tcTypes: str, baseTCTypes: str) -> PDM.ObjectCreateBuilder:
        ...
    def CreateMakeUniqueOperationBuilder(self, part: BasePart) -> PDM.PartOperationMakeUniqueBuilder:
        ...
    def CreateImportOperationBuilder(self) -> PDM.PartOperationImportBuilder:
        ...
    def CreatePartOperationAttributePropertiesBuilder(self, objects: typing.List[NXObject]) -> PDM.PartOperationAttributePropertiesBuilder:
        ...
    def CreatePartOperationValidationPropertiesBuilder(self, objects: typing.List[NXObject]) -> AttributePropertiesBuilder:
        ...
    def GetDatabaseObjectManager(self) -> PDM.DatabaseObjectManager:
        ...
    def CreateSmartSaveBuilder(self, saveType: PDM.SmartSaveBuilder.SaveType) -> PDM.SmartSaveBuilder:
        """[Obsolete("Deprecated in NX11.0.1.  Use NXOpen.PDM.PdmSession.CreateSmartSaveBuilderWithContext instead")"""
        ...
    def CreateSmartSaveContext(self, saveType: PDM.SmartSaveBuilder.SaveType) -> PDM.SmartSaveContext:
        ...
    def CreateSmartSaveContextWithDialogType(self, dialogType: PDM.SmartSaveBuilder.DialogType, saveType: PDM.SmartSaveBuilder.SaveType) -> PDM.SmartSaveContext:
        ...
    def CreateSmartSaveBuilderWithContext(self, smartSaveContext: PDM.SmartSaveContext) -> PDM.SmartSaveBuilder:
        ...
    def CreateExportWorksetForReferenceBuilder(self, workset: BasePart) -> PDM.ExportWorksetForReferenceBuilder:
        ...
    def SetActiveEngineeringChangeNotice(self, part: NXObject, ecnMFKId: str, ecnRevsionId: str) -> None:
        ...
    def SetNativeMode(self, enable: bool, rereadTemplateInformation: bool) -> None:
        ...
    def CreateExternalFileReferenceListBuilder(self, objects: typing.List[NXObject]) -> PDM.ExternalFileReferenceListBuilder:
        ...
    def GetCheckedoutStatusOfAllObjectsInSession(self, checkedOutObjects: typing.List[NXObject], uncheckedOutObjects: typing.List[NXObject]) -> None:
        ...
    def CreateFolder(self, newFolderName: str, parentFolderName: str) -> None:
        ...
    def GetItemTypes(self) -> str:
        ...
    def GetUserName(self) -> str:
        ...
    def GetUserGroup(self) -> str:
        ...
    def GetUserRole(self) -> str:
        ...
    def ExportFromTeamcenterCreate(self, part: TaggedObject) -> PDM.ExportFromTeamcenter:
        ...
    def CreatePdmCopyOrEditOperationBuilder(self) -> PDM.PdmCopyOrEditOperationBuilder:
        ...
    def CreatePdmCopyOrEditOperationAttributePropertiesBuilder(self, objects: typing.List[NXObject]) -> AttributePropertiesBuilder:
        ...
    def Tag(self) -> Tag: ...

    AttributeGroupDescriptions: PDM.AttributeGroupDescriptionCollection
    PartOperationImportObserver: PDM.PartOperationImportObserver
    SaveObserver: PDM.SaveManagement.SaveObserver
    SaveAsReviseObserver: PDM.SaveAsReviseObserver
    TcinUtils: PDM.TcinUtils
    PartNameGenerator: PDM.PartNameGenerator
    PartAttributeAssignmentObserver: PDM.PartAttributeAssignmentObserver
    PdmCopyOrEditOperationObserver: PDM.PdmCopyOrEditOperationObserver


class PdmSearchManager(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def NewPdmSearch(self) -> PDM.PdmSearch:
        ...
    def NewPdmSoaquery(self) -> PDM.SoaQuery:
        """[Obsolete("Deprecated in NX9.0.0.  This method is not useful. For NX Search use NXOpen.PDM.PdmSearchManager.NewPdmSearch instead")"""
        ...
    def NewPdmSearchresult(self) -> PDM.SearchResult:
        ...
    def NewPdmListofvalues(self) -> PDM.ListOfValues:
        ...
    def Tag(self) -> Tag: ...



class PdmSearch(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...
    def Advanced(self, entries: str, values: str) -> PDM.SearchResult:
        ...
    def Simple(self, searchCriteria: str) -> PDM.SearchResult:
        ...


class PdmPart(Utilities.NXRemotableObject):
    def __init__(self, owner: BasePart) -> None: ...
    def NewAlternateIdManager(self) -> PDM.AlternateIdManager:
        ...
    def NewDatabaseAttributeManager(self) -> PDM.DatabaseAttributeManager:
        ...
    def Checkout(self) -> None:
        ...
    def AssignPermanentName(self, newFileName: str) -> None:
        ...
    def SetDefaultFolderForPart(self) -> None:
        ...
    def CheckoutParts(self, partsToCheckOut: typing.List[BasePart], checkOutInput: PDM.PdmPart.CheckoutInput) -> PDM.OperationErrors:
        ...
    def CheckinParts(self, partsToCheckIn: typing.List[BasePart], checkInInput: PDM.PdmPart.CheckinInput) -> PDM.OperationErrors:
        ...
    def SetPreciseStructureOnSave(self, partsToSetPreciseOnSave: typing.List[BasePart]) -> None:
        ...
    def PublishHdImagesForModelViews(self, imageWidth: int, imageHight: int) -> None:
        ...
    def GetCheckedoutStatusAndUser(self, isCheckedOut: bool, checkedOutBy: str) -> None:
        ...
    def ListNonMasters(self, nonMasterFileType: str) -> str:
        ...
    def IsModifiable(self) -> bool:
        ...
    def GetOwnerAndGroup(self, owner: str, group: str) -> None:
        ...
    def GetProjects(self) -> str:
        ...
    def GetReleaseStatus(self) -> str:
        ...
    def ApplyVariantExpressions(self, pcaexpressionsInInput: typing.List[PDM.PdmPart.PcaexpressionsInput]) -> None:
        ...
    def GetRelatedDrawings(self) -> str:
        ...
    def ClearPreciseStructureOnSave(self, cancelPreciseOnSave: typing.List[BasePart]) -> None:
        ...
    def Tag(self) -> Tag: ...



    class PdmPartPcaexpressionsInput():
        Name: str
        Value: str
        Unit: str
        SavedVariants: str
        Optionfamily: str
        OptionName: str
        def ToString(self) -> str:
            ...
    

    class PdmPartCheckoutInput():
        InputComment: str
        InputChangeId: str
        AllowRemote: bool
        ExplicitCheckOut: bool
        IncludeSecondary: bool
        def ToString(self) -> str:
            ...
    

    class PdmPartCheckinInput():
        AllowRemote: bool
        ExplicitCheckIn: bool
        IncludeSecondary: bool
        def ToString(self) -> str:
            ...
        def __init__(self, AllowRemote: bool, ExplicitCheckIn: bool, IncludeSecondary: bool) -> None: ...
    

    class PdmPart_PcaexpressionsInput():
        name: int
        value: int
        unit: int
        savedVariants: int
        optionfamily: int
        optionName: int
    

    class PdmPart_CheckoutInput():
        inputComment: int
        inputChangeId: int
        allowRemote: bool
        explicitCheckOut: bool
        includeSecondary: bool
    

class PdmNavigatorNode(TreeListNode):
    def __init__(self) -> None: ...
    def GetUid(self) -> str:
        ...
    def GetNodeType(self) -> str:
        ...


class PdmFile(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...
    def GetFileName(self) -> str:
        ...
    def GetFileLastModifiedDate(self) -> str:
        ...
    def GetFileSize(self) -> str:
        ...


class PdmCopyOrEditOperationObserver(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int:
        ...
    def ToArray(self) -> typing.List[PDM.PdmCopyOrEditOperationCallbackData]:
        ...
    def __init__(self, owner: PDM.PdmSession) -> None: ...
    def __init__(self) -> None: ...
    def AddInitializeCallback(self, initializeCb: PDM.PdmCopyOrEditOperationObserver.InitializeCallback) -> int:
        ...
    def RemoveInitializeCallback(self, id: int) -> None:
        ...
    def AddPreAutoassignCallback(self, preAutoassignCb: PDM.PdmCopyOrEditOperationObserver.PreAutoassignCallback) -> int:
        ...
    def RemovePreAutoassignCallback(self, id: int) -> None:
        ...
    def AddPreCommitCallback(self, preCommitCb: PDM.PdmCopyOrEditOperationObserver.PreCommitCallback) -> int:
        ...
    def RemovePreCommitCallback(self, id: int) -> None:
        ...
    def AddPostCommitCallback(self, postCommitCb: PDM.PdmCopyOrEditOperationObserver.PostCommitCallback) -> int:
        ...
    def RemovePostCommitCallback(self, id: int) -> None:
        ...
    def AddTerminateCallback(self, terminateCb: PDM.PdmCopyOrEditOperationObserver.TerminateCallback) -> int:
        ...
    def RemoveTerminateCallback(self, id: int) -> None:
        ...
    def AddPreValidateCallback(self, preValidateCb: PDM.PdmCopyOrEditOperationObserver.PreValidateCallback) -> int:
        ...
    def RemovePreValidateCallback(self, id: int) -> None:
        ...
    def Tag(self) -> Tag: ...



    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

class PdmCopyOrEditOperationObject(NXObject):
    def __init__(self) -> None: ...
    def GetCurrentPrimaryLogicalObject(self) -> PDM.LogicalObject:
        ...
    def GetSecondaryLogicalObjects(self, secondaryLogicalObjects: typing.List[PDM.LogicalObject]) -> None:
        ...
    def GetInitialName(self) -> str:
        ...
    def GetFinalName(self) -> str:
        ...


class PdmCopyOrEditOperationCallbackData(TaggedObject):
    def __init__(self) -> None: ...
    def GetBuilder(self) -> PDM.PdmCopyOrEditOperationBuilder:
        ...


class PdmCopyOrEditOperationBuilder(PDM.PartOperationBuilder):
    def __init__(self) -> None: ...
    def AddParts(self, parts: str, errorMsgs: str) -> None:
        ...
    def AddPartsUsingCloneLogFile(self, logFilePath: str, errorMsgs: str) -> None:
        ...
    def ExecuteDryRun(self) -> None:
        ...
    def ValidateOperationObjects(self) -> None:
        ...
    def SetLoadOption(self, loadOption: LoadOptions.ManagedModeLoadMethod) -> None:
        ...
    def SetConfigurationContextUsingRevRule(self, setDefault: bool, revisionRuleName: str) -> int:
        ...
    def GetDefaultProjectInformation(self, projectNames: str, assignmentStates: typing.List[Session.ProjectAssignmentState]) -> None:
        ...
    def SetDefaultProjectInformation(self, projectNames: str, assignmentStates: typing.List[Session.ProjectAssignmentState]) -> None:
        ...
    def UpdateTeamcenterInformation(self, objects: typing.List[NXObject]) -> None:
        ...
    def ResetAttributes(self, objects: typing.List[NXObject]) -> None:
        ...
    def CreateOrUpdatePdmCopyOrEditOperationObjects(self, doUpdate: bool, copyOperationObjects: typing.List[PDM.PdmCopyOrEditOperationObject]) -> None:
        ...
    def GetPdmCopyOrEditOperationObjects(self, copyOperationObjects: typing.List[PDM.PdmCopyOrEditOperationObject]) -> None:
        ...
    def GetPdmCopyOrEditOperationObject(self, partFilename: str) -> PDM.PdmCopyOrEditOperationObject:
        ...
    def SetCloneAction(self, operationObject: PDM.PdmCopyOrEditOperationObject, cloneAction: PDM.PdmCopyOrEditOperationBuilder.CloneAction, modifiedLogicalObjects: typing.List[PDM.PdmCopyOrEditOperationObject]) -> None:
        ...
    def SetReplacePart(self, operationObject: PDM.PdmCopyOrEditOperationObject, replacePartCliSpec: str) -> int:
        ...
    def SetOverwritePart(self, operationObject: PDM.PdmCopyOrEditOperationObject, transientPartCliSpec: str) -> int:
        ...
    AssignAlternateIds: bool
    AssignDefaultChangeNotice: bool
    AttachLogFile: bool
    ConversionType: PDM.PdmCopyOrEditOperationBuilder.ConversionRule
    CopyAltrep: bool
    CopyAssociatedFiles: bool
    CopyCaeMotion: bool
    CopyCaeRelationOption: PDM.PdmCopyOrEditOperationBuilder.CaeRelationTraversalOption
    CopyCaeRelations: bool
    CopyDrawingRelations: bool
    CopyManifestation: bool
    CopySpecification: bool
    DefaultAction: PDM.PdmCopyOrEditOperationBuilder.CloneAction
    DefaultAlternateIdContext: str
    DefaultAlternateIdType: str
    DefaultChangeNotice: str
    DefaultOwningGroup: str
    DefaultOwningUser: str
    IncludeComponentParts: bool
    NumberingSource: PDM.PdmCopyOrEditOperationBuilder.NumberingSourceOption
    OutputLogFile: str
    PrefixStr: str
    RenumberStr: str
    ReplaceWithStr: str
    RetainOwnership: bool
    StringToReplace: str
    SuffixStr: str


    class NumberingSourceOption(enum.Enum):
        AutoGenerate = 0
        NamingRule = 1
        UserName = 2
    

    class ConversionRule(enum.Enum):
        WithPrefix = 0
        WithSuffix = 1
        WithReplaceString = 2
        WithRenumber = 3
        MixedRule = 4
    

    class CloneAction(enum.Enum):
        Clone = 0
        Retain = 1
        Revise = 2
        Replace = 3
        Overwrite = 4
    

    class CaeRelationTraversalOption(enum.Enum):
        SimFemIdeal = 0
        FemIdeal = 1
        Ideal = 2
        None = 3
    

class PdmCopyOrEditOperationAttributePropertiesBuilder(AttributePropertiesBuilder):
    def __init__(self) -> None: ...


class PartOperationValidationPropertiesBuilder(AttributePropertiesBuilder):
    def __init__(self) -> None: ...
    def GetValidationRuleSetBrowseOption(self) -> PDM.PartOperationImportBuilder.ValidationRuleSetFileBrowseOption:
        ...
    def SetValidationRuleSetBrowseOption(self, validationRuleSetBrowseOption: PDM.PartOperationImportBuilder.ValidationRuleSetFileBrowseOption) -> None:
        ...
    def GetValidationRuleSetFile(self) -> str:
        ...
    def SetValidationRuleSetFile(self, filename: str) -> None:
        ...
    def GetValidationTreatWarningAsPass(self) -> bool:
        ...
    def SetValidationTreatWarningAsPass(self, validationTreatWarningAsPass: bool) -> None:
        ...
    def GetValidationTreatOutdatedAsPass(self) -> bool:
        ...
    def SetValidationTreatOutdatedAsPass(self, validationTreatOutdatedAsPass: bool) -> None:
        ...


class PartOperationMakeUniqueBuilder(PDM.PartOperationCopyBuilder):
    def __init__(self) -> None: ...
    SelectedComponents: SelectDisplayableObjectList


class PartOperationImportObserver(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int:
        ...
    def ToArray(self) -> typing.List[PDM.PartOperationImportCallbackData]:
        ...
    def __init__(self, owner: PDM.PdmSession) -> None: ...
    def __init__(self) -> None: ...
    def AddInitializeCallback(self, initializeCb: PDM.PartOperationImportObserver.InitializeCb) -> int:
        ...
    def RemoveInitializeCallback(self, id: int) -> None:
        ...
    def AddPreAutoassignCallback(self, preAutoassignCb: PDM.PartOperationImportObserver.PreAutoassignCb) -> int:
        ...
    def RemovePreAutoassignCallback(self, id: int) -> None:
        ...
    def AddPreCommitCallback(self, preCommitCb: PDM.PartOperationImportObserver.PreCommitCb) -> int:
        ...
    def RemovePreCommitCallback(self, id: int) -> None:
        ...
    def AddPostCommitCallback(self, postCommitCb: PDM.PartOperationImportObserver.PostCommitCb) -> int:
        ...
    def RemovePostCommitCallback(self, id: int) -> None:
        ...
    def AddTerminateCallback(self, terminateCb: PDM.PartOperationImportObserver.TerminateCb) -> int:
        ...
    def RemoveTerminateCallback(self, id: int) -> None:
        ...
    def AddPreValidateCallback(self, preValidateCb: PDM.PartOperationImportObserver.PreValidateCb) -> int:
        ...
    def RemovePreValidateCallback(self, id: int) -> None:
        ...
    def Tag(self) -> Tag: ...



    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

class PartOperationImportCallbackData(TaggedObject):
    def __init__(self) -> None: ...
    def GetLogicalObjects(self, logicalObjects: typing.List[PDM.NativePartLogicalObject]) -> None:
        ...
    ImportBuilder: PDM.PartOperationImportBuilder


class PartOperationImportBuilder(PDM.PartOperationBuilder):
    def __init__(self) -> None: ...
    def AddParts(self, parts: str, errorMsgs: str) -> None:
        ...
    def AddPartsUsingLogFile(self, logFilePath: str, errorMsgs: str) -> None:
        ...
    def AddPartsFromFolder(self, folderPath: str, errorMsgs: str) -> None:
        ...
    def GetUpdatedLogicalObjects(self, logicalObjects: typing.List[PDM.LogicalObject]) -> None:
        ...
    def GetLogicalObjectForPart(self, partFilename: str) -> PDM.LogicalObject:
        ...
    def ResetAttributes(self, logicalObjects: typing.List[PDM.LogicalObject]) -> None:
        ...
    def ExecuteDryRun(self) -> None:
        ...
    def GetDefaultProjectInformation(self, projectNames: str, assignmentStates: typing.List[Session.ProjectAssignmentState]) -> None:
        ...
    def SetDefaultProjectInformation(self, projectNames: str, assignmentStates: typing.List[Session.ProjectAssignmentState]) -> None:
        ...
    def GetDfaFiles(self, dfaFiles: str) -> None:
        ...
    def SetDfaFiles(self, dfaFiles: str) -> None:
        ...
    def RemoveDfaFile(self, filename: str) -> None:
        ...
    def SetExistingPartAttributes(self, logicalObject: PDM.LogicalObject, existingPartCliSpec: str) -> None:
        ...
    def ValidateLogicalObjects(self) -> None:
        ...
    def UpdateTeamcenterInformation(self, logicalObjects: typing.List[PDM.LogicalObject]) -> None:
        ...
    def OnCancel(self) -> None:
        ...
    def GetExternalFileObjects(self, logicalObject: PDM.LogicalObject, objects: typing.List[NXObject]) -> None:
        ...
    AddCAENonMastersToImport: bool
    AddDfaMixins: bool
    AssignAlternateIds: bool
    AssociatedFilesRootDirectory: str
    CheckedoutCommentNotMatchError: bool
    CheckoutComment: str
    CheckoutOption: PDM.PartOperationImportBuilder.CheckoutOptionType
    ConversionType: PDM.PartOperationImportBuilder.ConversionRule
    DefaultAction: PDM.PartOperationImportBuilder.ExistingPartAction
    DefaultAlternateIdContext: str
    DefaultAlternateIdType: str
    DefaultChangeNotice: str
    DefaultDescription: str
    DefaultItemType: str
    DefaultName: str
    DefaultOwningGroup: str
    DefaultOwningUser: str
    IncludeComponentParts: bool
    IncludeDependentParts: bool
    NotCheckedoutError: bool
    NumberAttr: str
    NumberingSource: PDM.PartOperationImportBuilder.NumberingSourceOption
    OutputLogFile: str
    PrefixStr: str
    ProductInterfaces: bool
    PublishJTData: bool
    PublishOptionalInfo: bool
    ReplaceWithStr: str
    RevisionAttr: str
    StringToReplace: str
    SuffixStr: str
    SyncArrangements: bool
    UseItemTypeFromPartFile: bool
    ValidationAbortImportOnFail: bool
    ValidationMode: PDM.PartOperationImportBuilder.Validation
    ValidationRuleSetBrowseOption: PDM.PartOperationImportBuilder.ValidationRuleSetFileBrowseOption
    ValidationRuleSetFile: str
    ValidationTreatOutdatedAsPass: bool
    ValidationTreatWarningAsPass: bool


    class ValidationRuleSetFileBrowseOption(enum.Enum):
        Native = 0
        Teamcenter = 1
    

    class Validation(enum.Enum):
        Off = 0
        ImportFromPart = 1
        RunValidation = 2
        RunValidationHybrid = 3
        Default = 4
    

    class NumberingSourceOption(enum.Enum):
        PartIDGenerator = 0
        OSFilename = 1
        Attribute = 2
    

    class ExistingPartAction(enum.Enum):
        Overwrite = 0
        UseExisting = 1
        NewRevision = 2
        Default = 3
    

    class ConversionRule(enum.Enum):
        AsID = 0
        AsIDandRevision = 1
        WithPrefix = 2
        WithSuffix = 3
        WithReplaceString = 4
    

    class CheckoutOptionType(enum.Enum):
        Checkin = 0
        Checkout = 1
        NoChange = 2
    

class PartOperationCreateBuilder(PDM.PartOperationBuilder):
    def __init__(self) -> None: ...
    def SetItemType(self, itemType: str) -> None:
        ...
    def SetModelType(self, modelType: str) -> None:
        ...
    def SetMasterPart(self, masterPart: BasePart) -> None:
        ...
    def GetOperationSubType(self) -> PDM.PartOperationCreateBuilder.OperationSubType:
        ...
    def SetOperationSubType(self, operatioSubType: PDM.PartOperationCreateBuilder.OperationSubType) -> None:
        ...
    def SetAddMaster(self, addMaster: bool) -> None:
        ...
    def SetPartsToRename(self, partsToRename: typing.List[BasePart]) -> None:
        ...
    def GetAddMaster(self) -> bool:
        ...
    def SetPartSpecToOpen(self, partSpecToOpen: str) -> None:
        ...
    def CreateLogicalObjectsUsingSeedPart(self, seedPartName: str, numOfPartsToCreate: int, logicalObjects: typing.List[PDM.LogicalObject]) -> None:
        ...


    class OperationSubType(enum.Enum):
        FromTemplate = 0
        SelectTemplate = 1
        Rename = 2
        CreateSpecification = 3
        RenameNativePartInTc = 4
    

class PartOperationCopyBuilder(PDM.PartOperationBuilder):
    def __init__(self) -> None: ...
    def SetSelectedPartsToCopy(self, selectedParts: typing.List[BasePart], failedParts: typing.List[BasePart]) -> None:
        ...
    def AddRelatedPartsToCopy(self, basePart: BasePart, relatedParts: typing.List[BasePart], relatedPartsReasons: str, operation: PDM.PartOperationBuilder.OperationType) -> None:
        ...
    def CreateNonMasterListForCopyLogicalObject(self, logicalObject: PDM.LogicalObject) -> None:
        """[Obsolete("Deprecated in NX11.0.0.  Use NXOpen.PDM.NonMasterData.CreateNonMasterListForLogicalObject instead")"""
        ...
    def GetNonMasterListForCopyLogicalObject(self, logicalObject: PDM.LogicalObject) -> str:
        """[Obsolete("Deprecated in NX11.0.0.  Use NXOpen.PDM.NonMasterData.GetNonMasterListForCopyLogicalObject instead")"""
        ...
    def IsNonMasterForLogicalObjectBeingCopied(self, logicalObject: PDM.LogicalObject, partName: str) -> bool:
        """[Obsolete("Deprecated in NX11.0.0.  Use NXOpen.PDM.NonMasterData.IsNonMasterForLogicalObjectBeingCopied instead")"""
        ...
    def GetCopyNonMasterPartsOption(self, logicalObject: PDM.LogicalObject) -> PDM.PartOperationCopyBuilder.CopyNonMasterParts:
        """[Obsolete("Deprecated in NX11.0.0.  Use NXOpen.PDM.NonMasterData.GetCopyNonMasterPartsOption instead")"""
        ...
    def SetCopyNonMasterPartsOption(self, logicalObject: PDM.LogicalObject, saveOption: PDM.PartOperationCopyBuilder.CopyNonMasterParts) -> None:
        """[Obsolete("Deprecated in NX11.0.0.  Use NXOpen.PDM.NonMasterData.SetNonMasterSaveAsOption instead")"""
        ...
    def SetSelectedNonMasterToCopy(self, logicalObject: PDM.LogicalObject, partName: str) -> None:
        """[Obsolete("Deprecated in NX11.0.0.  Use NXOpen.PDM.NonMasterData.SetSelectedNonMasterToCopy instead")"""
        ...
    def EditNonMasterToCopyName(self, logicalObject: PDM.LogicalObject, oldName: str, newName: str) -> bool:
        """[Obsolete("Deprecated in NX11.0.0.  Use NXOpen.PDM.NonMasterData.EditNonMasterToCopyName instead")"""
        ...
    def GetOperationSubType(self) -> PDM.PartOperationCopyBuilder.OperationSubType:
        ...
    def SetOperationSubType(self, operationSubType: PDM.PartOperationCopyBuilder.OperationSubType) -> None:
        ...
    def GetSourcePartFromLogicalObject(self, logicalObject: PDM.LogicalObject) -> Part:
        ...
    DependentFilesToCopyOption: PDM.PartOperationCopyBuilder.CopyDependentFiles
    ReplaceAllComponentsInSession: bool


    class OperationSubType(enum.Enum):
        Default = 0
        MakeUnique = 1
    

    class CopyNonMasterParts(enum.Enum):
        All = 0
        None = 1
    

    class CopyDependentFiles(enum.Enum):
        All = 0
        None = 1
    

class PartOperationBuilder(Builder):
    def __init__(self) -> None: ...
    def CreateLogicalObjects(self, logicalObjects: typing.List[PDM.LogicalObject]) -> None:
        ...
    def GetDialogOperation(self) -> PDM.PartOperationBuilder.OperationType:
        ...
    def SetDialogOperation(self, dialogOperation: PDM.PartOperationBuilder.OperationType) -> None:
        ...
    def GetOperationFailures(self) -> ErrorList:
        """[Obsolete("Deprecated in NX12.0.0.  Use NXOpen.PDM.PartOperationBuilder.GetErrorMessageHandler instead")"""
        ...
    def GetAlternateIDManager(self, logicalObject: PDM.LogicalObject) -> PDM.AlternateIdManager:
        ...
    def CreateSpecificationsForLogicalObjects(self, logicalObjects: typing.List[PDM.LogicalObject]) -> None:
        ...
    def ValidateLogicalObjectsToCommit(self) -> None:
        ...
    def SetSelectedParts(self, selectedParts: typing.List[BasePart], failedParts: typing.List[BasePart]) -> None:
        """[Obsolete("Deprecated in NX10.0.0.  Use NXOpen.PDM.PartOperationCopyBuilder.SetSelectedPartsToCopy instead")"""
        ...
    def AddRelatedPartToOperate(self, basePart: BasePart, relatedParts: typing.List[BasePart], relatedPartsReasons: str, operation: PDM.PartOperationBuilder.OperationType) -> None:
        """[Obsolete("Deprecated in NX10.0.0.  Use NXOpen.PDM.PartOperationCopyBuilder.AddRelatedPartsToCopy instead")"""
        ...
    def CreateNonMasterListForLogicalObject(self, logicalObject: PDM.LogicalObject) -> None:
        """[Obsolete("Deprecated in NX10.0.0.  Use NXOpen.PDM.PartOperationCopyBuilder.CreateNonMasterListForCopyLogicalObject instead")"""
        ...
    def SetNonMasterSaveAsOption(self, logicalObject: PDM.LogicalObject, saveOption: PDM.PartOperationBuilder.NonMasterSaveAs) -> None:
        """[Obsolete("Deprecated in NX10.0.0.  Use NXOpen.PDM.PartOperationCopyBuilder.SetCopyNonMasterPartsOption instead")"""
        ...
    def SetSelectedNonMasterToSaveAs(self, logicalObject: PDM.LogicalObject, partName: str) -> None:
        """[Obsolete("Deprecated in NX10.0.0.  Use NXOpen.PDM.PartOperationCopyBuilder.SetSelectedNonMasterToCopy instead")"""
        ...
    def GetNonMasterList(self, logicalObject: PDM.LogicalObject) -> str:
        """[Obsolete("Deprecated in NX10.0.0.  Use NXOpen.PDM.PartOperationCopyBuilder.GetNonMasterListForCopyLogicalObject instead")"""
        ...
    def IsNonMasterBeingCopied(self, logicalObject: PDM.LogicalObject, partName: str) -> bool:
        """[Obsolete("Deprecated in NX10.0.0.  Use NXOpen.PDM.PartOperationCopyBuilder.IsNonMasterForLogicalObjectBeingCopied instead")"""
        ...
    def GetNonMasterCopyOption(self, logicalObject: PDM.LogicalObject) -> PDM.PartOperationBuilder.NonMasterSaveAs:
        """[Obsolete("Deprecated in NX10.0.0.  Use NXOpen.PDM.PartOperationCopyBuilder.GetCopyNonMasterPartsOption instead")"""
        ...
    def EditNonMasterName(self, logicalObject: PDM.LogicalObject, oldName: str, newName: str) -> bool:
        """[Obsolete("Deprecated in NX10.0.0.  Use NXOpen.PDM.PartOperationCopyBuilder.EditNonMasterToCopyName instead")"""
        ...
    def ClearWarnings(self) -> None:
        ...
    def GetErrorMessageHandler(self, refresh: bool) -> PDM.ErrorMessageHandler:
        ...
    def GetCreatedParts(self, commitedParts: typing.List[BasePart]) -> None:
        ...
    def AutoAssignAttributes(self, objects: typing.List[NXObject]) -> ErrorList:
        ...
    def AutoAssignAttributesWithNamingPattern(self, objects: typing.List[NXObject], properties: typing.List[NXObject]) -> ErrorList:
        ...
    def CreateAttributeTitleToNamingPatternMap(self, attributeTitles: str, titlePatterns: str) -> NXObject:
        ...
    DefaultDestinationFolder: str
    DependentFileSaveAsOption: PDM.PartOperationBuilder.DependentFileSaveAs
    ReplaceAllComponents: bool


    class OperationType(enum.Enum):
        SaveAs = 0
        Revise = 1
        Create = 2
        Import = 3
        Clone = 4
    

    class NonMasterSaveAs(enum.Enum):
        All = 0
        None = 1
    

    class DependentFileSaveAs(enum.Enum):
        All = 0
        None = 1
    

class PartOperationAttributePropertiesBuilder(AttributePropertiesBuilder):
    def __init__(self) -> None: ...
    def CreateOrModifyAttribute(self) -> bool:
        ...
    ReferenceObject: PDM.LogicalObject


class PartNameGenerator(Utilities.NXRemotableObject):
    def __init__(self, owner: PDM.PdmSession) -> None: ...
    def AutoAssignPartParametersForCreate(self, inputInfoPtr: PDM.PartNameGenerator.PartAssignInputInfo) -> str:
        ...
    def Tag(self) -> Tag: ...



    class PartNameGeneratorPartAssignInputInfo():
        ItemType: str
        ModelType: str
        BasePartNumber: str
        BasePartRevision: str
        BasePartName: str
        GenerateNextItemId: bool
        def ToString(self) -> str:
            ...
    

    class PartNameGenerator_PartAssignInputInfo():
        itemType: int
        modelType: int
        basePartNumber: int
        basePartRevision: int
        basePartName: int
        generateNextItemId: bool
    

class PartManager(Utilities.NXRemotableObject):
    def __init__(self, owner: PartCollection) -> None: ...
    def NewPartFromTemplateBuilder(self) -> PDM.PartFromTemplateBuilder:
        """[Obsolete("Deprecated in NX10.0.0.  Use NXOpen.PDM.PartOperationCreateBuilder instead.")"""
        ...
    def NewPartFromPartBuilder(self) -> PDM.PartFromPartBuilder:
        ...
    def NewPendingComponentsManager(self, part: BasePart) -> PDM.PendingComponentsManager:
        ...
    def GetCaeCloneManager(self, part: BasePart) -> PDM.CaeCloneManager:
        """[Obsolete("Deprecated in NX10.0.0.  Use NXOpen.PDM.PartOperationCopyBuilder instead.")"""
        ...
    def Tag(self) -> Tag: ...



class PartFromTemplateBuilder(PDM.PartBuilder):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...
    def SetSeedPart(self, seedName: str) -> None:
        """[Obsolete("Deprecated in NX10.0.0.  Use PDM.PartOperationCreateBuilder instead.")"""
        ...
    def Commit(self) -> BasePart:
        """[Obsolete("Deprecated in NX10.0.0.  Use PDM.PartOperationCreateBuilder instead.")"""
        ...
    def Commit(self, setAsDisplayPart: bool) -> BasePart:
        """[Obsolete("Deprecated in NX10.0.0.  Use PDM.PartOperationCreateBuilder instead.")"""
        ...


class PartFromPartBuilder(PDM.PartBuilder):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...
    def CreateNonmasterList(self) -> None:
        ...
    def GetNonmasterList(self) -> str:
        ...
    def GetNonmasterToSaveAs(self, partName: str) -> bool:
        ...
    def SetNonmasterToSaveAs(self, partName: str, doSaveAs: bool) -> None:
        ...
    def EditNonmasterNameToSaveAs(self, oldName: str, newName: str) -> bool:
        ...
    def Commit(self) -> None:
        ...
    DependentFileSaveAsOption: PDM.PartFromPartBuilder.FileSaveAs
    NonmasterSaveAsOption: PDM.PartFromPartBuilder.FileSaveAs


    class FileSaveAs(enum.Enum):
        Some = 0
        All = 1
        None = 2
    

class PartFamilyTreatment(enum.Enum):
    TreatAsLostPart = 0
    TurnIntoNormalPart = 1


class PartCreationObjectAttributePropertiesBuilder(AttributePropertiesBaseBuilder):
    def __init__(self) -> None: ...


class PartCreationObject(NXObject):
    def __init__(self) -> None: ...
    def CreateAttributePropertiesBuilder(self) -> PDM.PartCreationObjectAttributePropertiesBuilder:
        """[Obsolete("Deprecated in NX8.5.0.  Use AttributeManager.CreateAttributePropertiesBuilder instead.")"""
        ...


class PartBuilder(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...
    def CreatePartSpec(self, partType: str, partNumber: str, partRevision: str, partFileType: str, partFileName: str) -> None:
        ...
    def NewDatabaseAttributeManager(self) -> PDM.DatabaseAttributeManager:
        ...
    def CreatePartCreationObject(self) -> PDM.PartCreationObject:
        ...
    def NewAlternateIdManager(self) -> PDM.AlternateIdManager:
        ...
    def AssignPartNumber(self, partType: str) -> str:
        ...
    def AssignPartRevision(self) -> str:
        ...
    def AssignPartFileName(self, partFileType: str) -> str:
        ...
    def AssignPartNumber(self, oldPartNumber: str, partType: str) -> PDM.PartBuilder.PartNumberData:
        ...
    def AssignPartRevision(self, overload: int) -> PDM.PartBuilder.PartRevisionData:
        ...
    def AssignPartFileName(self, partNumber: str, partRevision: str, partFileNameType: str, oldPartFileName: str) -> PDM.PartBuilder.PartFileNameData:
        ...
    def SetAssignPartNumber(self, partNumber: str) -> None:
        ...
    def SetAssignPartType(self, partType: str) -> None:
        ...
    def SetContextOperation(self, operation: PDM.PartBuilder.Operation) -> None:
        ...


    class PartBuilderPartRevisionData():
        PartRevision: str
        PartRevisionModifiable: bool
        def ToString(self) -> str:
            ...
        def __init__(self, PartRevision: str, PartRevisionModifiable: bool) -> None: ...
    

    class PartBuilderPartNumberData():
        PartName: str
        PartNameModifiable: bool
        PartDescription: str
        PartDescriptionModifiable: bool
        PartNumber: str
        PartNumberModifiable: bool
        def ToString(self) -> str:
            ...
    

    class PartBuilderPartFileNameData():
        PartFileName: str
        PartFileNameModifiable: bool
        def ToString(self) -> str:
            ...
        def __init__(self, PartFileName: str, PartFileNameModifiable: bool) -> None: ...
    

    class Operation(enum.Enum):
        ExportPartNew = 0
        AssemblyDiagram = 1
        AssemblyCreateNewComponent = 2
        Default = 3
    

    class PartBuilder_PartRevisionData():
        part_revision: int
        part_revision_modifiable: bool
    

    class PartBuilder_PartNumberData():
        part_name: int
        part_name_modifiable: bool
        part_description: int
        part_description_modifiable: bool
        part_number: int
        part_number_modifiable: bool
    

    class PartBuilder_PartFileNameData():
        part_file_name: int
        part_file_name_modifiable: bool
    

class PartAttributeAssignmentObserverCallbackData(TaggedObject):
    def __init__(self) -> None: ...
    def GetLogicalObjects(self, logicalObjects: typing.List[PDM.LogicalObject]) -> None:
        ...


class PartAttributeAssignmentObserver(Utilities.NXRemotableObject):
    def __init__(self, owner: PDM.PdmSession) -> None: ...
    def RegisterUserDefinedFunction(self, handler: PDM.PartAttributeAssignmentObserver.UserFunctionHandler) -> int:
        ...
    def UnRegisterUserDefinedFunction(self, id: int) -> None:
        ...
    def Tag(self) -> Tag: ...



    

    

    

class OrderedElementGroup(NXObject):
    def __init__(self) -> None: ...


class OperationErrors(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...


class ObjectCreateBuilder(Builder):
    def __init__(self) -> None: ...
    def SetTypes(self, tcTypes: str, baseTCTypes: str) -> None:
        ...
    def CreateLogicalObjects(self, logicalObjects: typing.List[PDM.LogicalObject]) -> None:
        ...
    def GetAttributeHolderObjects(self, attributeHolderObjects: typing.List[PDM.GenericObjectAttributeHolder]) -> None:
        ...
    def AutoAssignAttributes(self, objects: typing.List[NXObject]) -> ErrorList:
        ...
    def AutoAssignAttributesWithNamingPattern(self, objects: typing.List[NXObject], properties: typing.List[NXObject]) -> ErrorList:
        ...
    def CreateAttributeTitleToNamingPatternMap(self, attributeTitles: str, titlePatterns: str) -> NXObject:
        ...
    DefaultDestinationFolder: str


class NonMasterData(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...
    def CreateNonMasterListForLogicalObject(self, logicalObject: PDM.LogicalObject) -> None:
        ...
    def GetNonMasterListForCopyLogicalObject(self, logicalObject: PDM.LogicalObject) -> str:
        ...
    def IsNonMasterForLogicalObjectBeingCopied(self, logicalObject: PDM.LogicalObject, partName: str) -> bool:
        ...
    def GetCopyNonMasterPartsOption(self, logicalObject: PDM.LogicalObject) -> PDM.NonMasterData.CopyNonMasterPartsOption:
        ...
    def SetNonMasterSaveAsOption(self, logicalObject: PDM.LogicalObject, saveOption: PDM.NonMasterData.CopyNonMasterPartsOption) -> None:
        ...
    def SetSelectedNonMasterToCopy(self, logicalObject: PDM.LogicalObject, partName: str) -> None:
        ...
    def EditNonMasterToCopyName(self, logicalObject: PDM.LogicalObject, oldName: str, newName: str) -> bool:
        ...


    class CopyNonMasterPartsOption(enum.Enum):
        All = 0
        None = 1
    

class NativePartLogicalObject(PDM.LogicalObject):
    def __init__(self) -> None: ...
    def GetInitialName(self) -> str:
        ...
    def GetFinalName(self) -> str:
        ...
    def IsPartNameAutoAssigned(self) -> bool:
        ...
    def IsCandidateForImport(self) -> bool:
        ...
    def GetExistingPartAction(self) -> PDM.PartOperationImportBuilder.ExistingPartAction:
        ...
    def SetExistingPartAction(self, existingPartAction: PDM.PartOperationImportBuilder.ExistingPartAction) -> None:
        ...
    def GetValidationMode(self) -> PDM.PartOperationImportBuilder.Validation:
        ...
    def SetValidationMode(self, validationMode: PDM.PartOperationImportBuilder.Validation) -> None:
        ...
    def GetValidationRuleSetFileBrowseOption(self) -> PDM.PartOperationImportBuilder.ValidationRuleSetFileBrowseOption:
        ...
    def SetValidationRuleSetFileBrowseOption(self, browseOption: PDM.PartOperationImportBuilder.ValidationRuleSetFileBrowseOption) -> None:
        ...


class NamingTechniqueOption(enum.Enum):
    AutoTranslate = 0
    NamingRule = 1
    AutoTranslateWithAlternateID = 2
    UserName = 3
    AutoGenerate = 4
    Default = 5


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class ModelElementRevision(NXObject):
    def __init__(self) -> None: ...
    def GetMemberPartitions(self) -> typing.List[Assemblies.Partition]:
        ...
    def GetOverridePart(self) -> Part:
        ...
    def IsExcludedFromSpatialSearch(self) -> bool:
        ...
    def SetExcludeFromSpatialSearch(self, excludeFromSpatialSearch: bool) -> None:
        ...
    def GetPositionStatus(self) -> PDM.ModelElementRevision.PositioningStatus:
        ...
    def IsAbsolutelyPositioned(self) -> bool:
        ...
    def GetPositioningGroups(self) -> typing.List[Assemblies.PositioningGroup]:
        ...
    def IsMemberOfPositioningGroup(self) -> bool:
        ...
    def Create(self, attributeGroupDescription: PDM.AttributeGroupDescription) -> PDM.AttributeGroup:
        ...
    def CreateAttributeGroupReviseBuilder(self, attributeGroups: typing.List[PDM.AttributeGroup]) -> PDM.AttributeGroupReviseBuilder:
        ...
    def GetAttributeGroups(self) -> typing.List[PDM.AttributeGroup]:
        ...
    def GetAttributeGroupDescriptions(self) -> typing.List[PDM.AttributeGroupDescription]:
        ...
    def CreateAttributeGroupReviseBuilder(self, attributeGroups: typing.List[PDM.AttributeGroup], keepOriginal: bool, saveAsActionType: PDM.AttributeGroupReviseBuilder.SaveAsActionType) -> PDM.AttributeGroupReviseBuilder:
        ...
    EffectivityFormula: str
    OwningCollaborativeDesign: CollaborativeDesign


    class PositioningStatus(enum.Enum):
        AbsolutelyPositioned = 0
        OutOfDate = 1
        UpToDate = 2
        Unknown = 3
    

class ModelElement(NXObject):
    def __init__(self) -> None: ...
    def GetMemberPartitions(self) -> typing.List[Assemblies.Partition]:
        ...
    def Create(self, attributeGroupDescription: PDM.AttributeGroupDescription) -> PDM.AttributeGroup:
        ...
    def CreateAttributeGroupReviseBuilder(self, attributeGroups: typing.List[PDM.AttributeGroup]) -> PDM.AttributeGroupReviseBuilder:
        ...
    def GetAttributeGroups(self) -> typing.List[PDM.AttributeGroup]:
        ...
    def GetAttributeGroupDescriptions(self) -> typing.List[PDM.AttributeGroupDescription]:
        ...
    def CreateAttributeGroupReviseBuilder(self, attributeGroups: typing.List[PDM.AttributeGroup], keepOriginal: bool, saveAsActionType: PDM.AttributeGroupReviseBuilder.SaveAsActionType) -> PDM.AttributeGroupReviseBuilder:
        ...
    OwningCollaborativeDesign: CollaborativeDesign


class LogicalObject(NXObject):
    def __init__(self) -> None: ...


class LogicalElementRevision(PDM.ConditionalElementRevision):
    def __init__(self) -> None: ...


class ListOfValues(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...


class ICloneOperation(TaggedObject):
    def __init__(self) -> None: ...
    def AddPart(self, partName: str) -> None:
        ...
    def AddAssembly(self, assemblyName: str) -> PartLoadStatus:
        ...
    def LoadFromLogFile(self, logFileName: str, namingFailures: AssyCloneNamingFailures, logFileFailures: AssyCloneLogFileFailures, loadStatus: PartLoadStatus) -> None:
        ...
    def Destroy(self) -> None:
        ...
    def ApplyDefaultsAndExecute(self, skipExecute: bool, namingFailures: AssyCloneNamingFailures, namingWarnings: AssyCloneNamingFailures) -> None:
        ...
    def TerminateOperation(self) -> None:
        ...
    def SetNamingTechnique(self, namingTechnique: PDM.NamingTechniqueOption) -> None:
        ...
    def SetDefaultAction(self, defaultAction: PDM.ExistingPartAction) -> None:
        ...
    def SetPrefixString(self, prefixStr: str) -> None:
        ...
    def SetSuffixString(self, suffixStr: str) -> None:
        ...
    def ReplaceString(self, baseString: str, newString: str) -> None:
        ...
    def RenameString(self, renameStr: str) -> None:
        ...
    def SetOutputLogFile(self, logFileName: str) -> None:
        ...
    def AttachLogFileToAssociatedFiles(self, attachLogFileToAssociatedFiles: bool) -> None:
        ...
    def SetCloneRelatedCae(self, cloneRelatedCae: PDM.CloneRelatedCae) -> None:
        ...
    def SetCloneRelatedDrawings(self, cloneRelatedDrawings: bool) -> None:
        ...
    def CopyAssociatedFiles(self, copyAssociatedFiles: bool) -> None:
        ...
    def CopyRelations(self, relationTypes: str, copyRelations: bool) -> None:
        ...
    def AssignCompDisposition(self, objectToBeCloned: PDM.AssyCloneCompDisp, action: PDM.ExistingPartAction, cascadeDispositions: bool, cascadedComponentDispositions: typing.List[PDM.AssyCloneCompDisp], conflictingComponentDispositions: typing.List[PDM.AssyCloneCompDisp]) -> None:
        ...
    def AssignCloneNaming(self, objectToBeCloned: PDM.AssyCloneCompDisp, namingTechnique: PDM.NamingTechniqueOption, finalName: str) -> int:
        ...
    def FetchObjects(self, objectsToBeCloned: typing.List[PDM.AssyCloneCompDisp]) -> None:
        ...
    def SetDryRun(self, isDryRun: bool) -> None:
        ...
    def SetFinalName(self, objectToBeCloned: PDM.AssyCloneCompDisp, finalName: str, allowDuplicates: bool) -> None:
        ...
    def SetConfigurationContextUsingRevRule(self, setDefault: bool, revisionRuleName: str) -> int:
        ...
    def SetLoadOption(self, loadOption: LoadOptions.ManagedModeLoadMethod) -> None:
        ...
    def InitCloneLog(self, logFileName: str) -> None:
        ...
    def ReprocessNonComponentReferences(self) -> None:
        ...
    def ApplyCICODefaults(self) -> AssyCloneNamingFailures:
        ...
    def PerformPreCommit(self) -> None:
        ...
    def PerformPostCommit(self) -> None:
        ...
    def AddApplicationRelatedParts(self) -> None:
        ...
    def SetPartFamilyTreatment(self, partFamilyTreatment: PDM.PartFamilyTreatment) -> None:
        ...
    def SetCloneExcludeReferenceOnly(self, excludeReferenceOnly: bool) -> None:
        ...
    def SetCloneExcludeNGC(self, excludeNGC: bool) -> None:
        ...
    def AutoAssignAttributes(self, objects: typing.List[NXObject]) -> ErrorList:
        ...
    def AutoAssignAttributesWithNamingPattern(self, objects: typing.List[NXObject], properties: typing.List[NXObject]) -> ErrorList:
        ...
    def CreateAttributeTitleToNamingPatternMap(self, attributeTitles: str, titlePatterns: str) -> NXObject:
        ...


class IAttributeGroupOwner():
    def Create(self, attributeGroupDescription: PDM.AttributeGroupDescription) -> PDM.AttributeGroup:
        ...
    def CreateAttributeGroupReviseBuilder(self, attributeGroups: typing.List[PDM.AttributeGroup]) -> PDM.AttributeGroupReviseBuilder:
        ...
    def GetAttributeGroups(self) -> typing.List[PDM.AttributeGroup]:
        ...
    def GetAttributeGroupDescriptions(self) -> typing.List[PDM.AttributeGroupDescription]:
        ...
    def CreateAttributeGroupReviseBuilder(self, attributeGroups: typing.List[PDM.AttributeGroup], keepOriginal: bool, saveAsActionType: PDM.AttributeGroupReviseBuilder.SaveAsActionType) -> PDM.AttributeGroupReviseBuilder:
        ...


class GenericObjectAttributeHolder(NXObject):
    def __init__(self) -> None: ...


class FindCriteria(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...
    def SetCriteria(self, queryName: str, entries: str, values: str) -> None:
        ...
    def GetCriteria(self, queryName: str, entries: str, values: str) -> None:
        ...


class FileManagement(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...
    def ImportFiles(self, itemIds: str, itemRevisionIds: str, datasetNames: str, datasetTypeNames: str, datasetRelationTypeNames: str, importDirectoryNames: str) -> int:
        ...
    def ExportFiles(self, itemIds: str, itemRevisionIds: str, datasetNames: str, datasetTypeNames: str, datasetRelationTypeNames: str, baseDirectoryNames: str, toolNames: str, exportDirectoryNames: str) -> int:
        ...
    def GetAssociatedFiles(self, parts: typing.List[BasePart], fileTypesToExclude: typing.List[PDM.FileManagement.FileType]) -> typing.List[PDM.PdmFile]:
        ...
    def DownloadAssociatedFiles(self, parts: typing.List[BasePart], files: typing.List[PDM.PdmFile]) -> None:
        ...
    def ImportFilesAndCreateDatasets(self, itemIds: str, itemRevisionIds: str, datasetNames: str, datasetTypeNames: str, datasetRelationTypeNames: str, datasetToolNames: str, fileType: bool, namedReferenceNames: str, importFileNames: str, importFileDirectoryNames: str) -> int:
        ...
    def ExportNamedReferences(self, itemId: str, itemRevisionId: str, datasetName: str, datasetTypeName: str, datasetRelationTypeName: str, datasetNamedReference: str, exportDirectoryName: str, namedReferences: str) -> None:
        ...
    def ExportNamedReferences(self, itemIds: str, itemRevisionIds: str, datasetNames: str, datasetTypeNames: str, datasetRelationTypeNames: str, datasetNamedReferences: str, exportDirectoryName: str, numNamedReferences: int, namedReferences: str) -> int:
        ...
    def SaveAttachedFiles(self, associatedObject: typing.List[NXObject], associationTypeName: str, datasetTypeName: str, datasetName: str, numDatasetPropertyInput: int, datasetPropertyNames: str, datasetPropertyValues: str, ownershipToMatchForNewDataset: typing.List[NXObject], fileVolumeToStore: typing.List[PDM.PdmFile], toolUsed: str, datasetDescription: str, alwaysCreateNewDataset: bool, createNewDatasetVersion: bool, refreshInSessionLoadedLMD: bool, numNamedReferencesPerInput: int, namedReferenceName: str, isText: bool, filePath: str, logicalFileName: str, allowReplace: bool, outputFiles: bool, files: typing.List[PDM.PdmFile]) -> int:
        ...
    def DeleteAttachedFiles(self, associatedObject: typing.List[NXObject], associationTypeName: str, datasetTypeName: str, datasetName: str, namedReferenceName: str, isText: str, logicalFileName: str, keepEmptyDataset: bool) -> int:
        ...
    def DeleteExistingAttachedFiles(self, files: typing.List[PDM.PdmFile], keepEmptyDataset: bool) -> int:
        ...
    def GetAttachedFiles(self, associatedObject: typing.List[NXObject], associationTypeName: str, datasetTypeName: str, datasetName: str, namedReferenceName: str, isText: str, logicalFileName: str, exportDirectoryName: str, numOutputFiles: int, files: typing.List[PDM.PdmFile]) -> int:
        ...


    class FileType(enum.Enum):
        CmmDmi = 0
        CpdFeaturePart = 1
        CpdGeometryOverride = 2
        DirectModel = 3
        Excel = 4
        ExcelX = 5
        Image = 6
        Jpeg = 7
        NxDesignatorAssignmentsFile = 8
        NxAttachedPart = 9
        NxPart = 10
        NxPosBin = 11
        NxleSymbolXml = 12
        NxleSymbolPreview = 13
        Preview2d = 14
        Preview3d = 15
        QafBinary = 16
        QafText = 17
        RoutePipeRun = 18
        RoutePipeSpec = 19
        RoutePipeRunAttachment = 20
        Text = 21
        Tif = 22
        TrushapeData = 23
        ValidationRuleSet = 24
    

class ExternalFileReferenceListBuilder(Builder):
    def __init__(self) -> None: ...
    def GetExternalFileObjects(self, objects: typing.List[NXObject]) -> None:
        ...
    def AutoAssignAttributes(self, objects: typing.List[NXObject]) -> ErrorList:
        ...
    def AutoAssignAttributesWithNamingPattern(self, objects: typing.List[NXObject], properties: typing.List[NXObject]) -> ErrorList:
        ...
    def CreateAttributeTitleToNamingPatternMap(self, attributeTitles: str, titlePatterns: str) -> NXObject:
        ...


class ExportWorksetForReferenceBuilder(Builder):
    def __init__(self) -> None: ...
    def GetObjects(self, objects: typing.List[NXObject]) -> None:
        ...
    def ValidateObjects(self) -> ErrorList:
        ...
    def AutoAssignAttributes(self, objects: typing.List[NXObject]) -> ErrorList:
        ...
    def AutoAssignAttributesWithNamingPattern(self, objects: typing.List[NXObject], properties: typing.List[NXObject]) -> ErrorList:
        ...
    def CreateAttributeTitleToNamingPatternMap(self, attributeTitles: str, titlePatterns: str) -> NXObject:
        ...
    DestinationFolder: str


class ExportFromTeamcenter(PDM.ICloneOperation):
    def __init__(self) -> None: ...
    def SetDefaultDirectory(self, directoryName: str) -> None:
        ...
    def SetAssociatedFilesRootDir(self, rootDirName: str) -> None:
        ...
    def SetAssociatedFilesDir(self, objectToBeCloned: PDM.AssyCloneCompDisp, directoryName: str) -> None:
        ...
    def SetExternalFiles(self, setExternalFiles: bool) -> None:
        ...
    def CreateZipFileOfExportedParts(self, zipFilePath: str, overwrite: bool) -> int:
        ...
    def SetDefaultCheckOutData(self, checkoutComment: str) -> None:
        ...
    def SetCheckOutData(self, objectToBeCloned: PDM.AssyCloneCompDisp, checkoutComment: str) -> int:
        ...
    def SetAddDfaMixins(self, isAddDfaMixins: bool) -> None:
        ...
    def SetExportDfaWithPart(self, isExportDfaWithPart: bool) -> None:
        ...
    def AddDFAFile(self, dfaFile: str) -> None:
        ...
    def ExportDFAFiles(self, dfaFiles: str, defDir: str, doMixins: bool) -> None:
        ...
    def SetIdentifierDisplayRule(self, displayRule: str) -> None:
        ...


class ExistingPartAction(enum.Enum):
    Overwrite = 0
    UseExisting = 1
    Exclude = 2
    Clone = 3
    Retain = 4
    Default = 5


class ErrorMessageHandler(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...
    def GetErrorList(self) -> ErrorList:
        ...
    def GetErrorMessages(self) -> str:
        ...
    def GetWarningMessages(self) -> str:
        ...


class ElementGroup(PDM.ConditionalElementRevision):
    def __init__(self) -> None: ...


class EffectivityTableRow(NXObject):
    def __init__(self) -> None: ...


class EffectivityTableBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def GetEffectivityRows(self, effectivityRows: typing.List[PDM.EffectivityTableRow]) -> None:
        ...
    def CreateNewEffectivityRow(self) -> PDM.EffectivityTableRow:
        ...
    def AddEffectivityRow(self, effectivityRow: PDM.EffectivityTableRow) -> None:
        ...
    def RemoveEffectivityRows(self, effectivityRows: typing.List[PDM.EffectivityTableRow]) -> None:
        ...
    def UpdateBuilderDetails(self, cd: CollaborativeDesign, validationBasisFormula: str, effectivityFormulae: str) -> None:
        ...
    def Commit(self) -> None:
        ...
    def Validate(self) -> bool:
        ...


class EffectivityAttributePropertiesBuilder(Builder):
    def __init__(self) -> None: ...
    def Delete(self, object: NXObject) -> None:
        ...
    def CreateAttribute(self) -> bool:
        ...
    def SetAttributeObjects(self, objects: typing.List[NXObject]) -> None:
        ...
    Category: str
    DisplayValue: str
    EffectivityTableBuilder: PDM.EffectivityTableBuilder
    SelectedObjects: SelectNXObjectList
    StringValue: str
    Title: str


class DesignSubordinateRevision(PDM.ModelElementRevision):
    def __init__(self) -> None: ...
    DesignPart: Part
    Modified: bool
    RootDesignElementRevision: PDM.DesignElementRevision


class DesignFeatureRevision(PDM.ModelElementRevision):
    def __init__(self) -> None: ...


class DesignElementRevision(PDM.ModelElementRevision):
    def __init__(self) -> None: ...
    def GetTransform(self, positionInMeters: Point3d) -> Matrix3x3:
        ...
    def GetDesignSubordinateRevisions(self) -> typing.List[PDM.DesignSubordinateRevision]:
        ...
    Category: PDM.DesignElementRevision.DesignElementCategory
    DesignPart: Part
    Modified: bool


    class DesignElementCategory(enum.Enum):
        Shape = 0
        Reuse = 1
        Promissory = 2
        DesignControlElement = 3
    

class DBEntityProxyCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int:
        ...
    def ToArray(self) -> typing.List[PDM.DBEntityProxy]:
        ...
    def __init__(self, owner: Part) -> None: ...
    def __init__(self) -> None: ...
    def FindProxy(self, journalIdentifier: str) -> NXObject:
        ...
    def CreateDbEntityProxy(self, title: str, index: int, context: TaggedObject, attributeOwner: TaggedObject) -> PDM.DBEntityProxy:
        ...
    def Tag(self) -> Tag: ...



class DBEntityProxy(NXObject):
    def __init__(self) -> None: ...


class DatabaseObjects(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...
    def SetDatabaseObjects(self, databaseObjects: typing.List[PDM.DatabaseObject]) -> None:
        ...
    def GetDatabaseObjects(self) -> typing.List[PDM.DatabaseObject]:
        ...
    def Append(self, databaseObjects: typing.List[PDM.DatabaseObjects]) -> None:
        ...


class DatabaseObjectManager(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...
    def NewFindcriteria(self, nCriteria: int) -> typing.List[PDM.FindCriteria]:
        ...
    def NewDatabaseobjects(self) -> PDM.DatabaseObjects:
        ...
    def FindObjects(self, findCriterias: typing.List[PDM.FindCriteria]) -> typing.List[PDM.DatabaseObjects]:
        ...
    def GetDatabaseObjectFromAppSessionUid(self, uId: str) -> PDM.DatabaseObject:
        ...
    def FindDesignSessionObjects(self, designSessionParamNames: str, designSessionParamValues: str) -> PDM.DatabaseObject:
        ...


class DatabaseObject(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...


class DatabaseAttributeManager(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...
    def SetAttribute(self, attributeTitle: str, attributeValue: str) -> None:
        ...
    def GetAttribute(self, attributeTitle: str) -> str:
        ...
    def StoreAttributes(self) -> None:
        ...
    def RefreshAttributes(self) -> None:
        ...
    def LoadAttributes(self, reload: bool) -> None:
        ...
    def LoadAttributesRecursively(self, reload: bool) -> None:
        ...


class CustomWebAppMenuHandler(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...
    def RegisterCustomWebAppInvokedCallback(self, webappCb: PDM.CustomWebAppMenuHandler.CustomWebAppInvokedCallback) -> None:
        ...
    def GetSelectedUids(self, uids: str) -> None:
        ...
    def GetCommandName(self) -> str:
        ...


    

    

    

class CrossSheetReference(PDM.ModelElement):
    def __init__(self) -> None: ...


class ConversionRule(enum.Enum):
    WithPrefix = 0
    WithSuffix = 1
    WithReplaceString = 2
    WithRename = 3


class ConnectionElementRevision(PDM.ConditionalElementRevision):
    def __init__(self) -> None: ...


class ConfigurationManager(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def CreateConfigurationContextBuilder(self) -> PDM.ConfigurationContextBuilder:
        ...
    def CreateEffectivityAttributePropertiesBuilder(self, part: BasePart, objects: typing.List[NXObject]) -> PDM.EffectivityAttributePropertiesBuilder:
        ...
    def CreateVariantRulesConfigurationBuilder(self, part: BasePart) -> PDM.VariantRulesConfigurationBuilder:
        ...
    def Tag(self) -> Tag: ...



class ConfigurationContextBuilder(Builder):
    def __init__(self) -> None: ...
    CollaborativeDesign: CollaborativeDesign
    ConfigDetail: PDM.ConfigurationContextBuilder.ConfigurationDetail
    ConfigMode: PDM.ConfigurationContextBuilder.ConfigContextMode
    ConfigType: PDM.ConfigurationContextBuilder.ConfigContextType
    ContentDefinition: ContentDefinition
    EffectivityTable: PDM.EffectivityTableBuilder
    OverrideFolder: str
    RevisionRule: str
    VariantConfiguration: PDM.VariantConfigurationBuilder


    class ConfigurationDetail(enum.Enum):
        LoadfromTeamcenter = 0
        DefineinNX = 1
    

    class ConfigContextType(enum.Enum):
        AsSaved = 0
        PushedfromTeamcenter = 1
        DefineorLoadContext = 2
    

    class ConfigContextMode(enum.Enum):
        Nx4gd = 0
        Assemblies = 1
    

class ConditionalElementRevision(PDM.ModelElement):
    def __init__(self) -> None: ...
    EffectivityFormula: str


class CloneRelatedCae(enum.Enum):
    SimFemIdeal = 0
    FemIdeal = 1
    Ideal = 2
    None = 3


class CAEFileContainer(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...
    def GetOwningPart(self) -> str:
        ...
    def SetOwningPart(self, partspec: str) -> None:
        ...
    def AddFile(self, datasetname: str, filename: str) -> None:
        ...
    def DeleteFile(self, datasetname: str, filename: str) -> None:
        ...
    def DoUpload(self) -> None:
        ...


class CaeCloneManager(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        """[Obsolete("Deprecated in NX10.0.0.  Use NXOpen.PDM.PartOperationCopyBuilder instead.")"""
        ...
    def GetPartBuilderForClone(self, option: PDM.CaeCloneManager.CloneOption) -> PDM.PartFromPartBuilder:
        """[Obsolete("Deprecated in NX10.0.0.  Use NXOpen.PDM.PartOperationCopyBuilder instead.")"""
        ...
    def SetIncludeMaster(self, value: bool) -> None:
        """[Obsolete("Deprecated in NX10.0.0.  Use NXOpen.PDM.PartOperationCopyBuilder instead.")"""
        ...
    def GetContainer(self, option: PDM.CaeCloneManager.CloneOption) -> str:
        """[Obsolete("Deprecated in NX10.0.0.  Use NXOpen.PDM.PartOperationCopyBuilder instead.")"""
        ...
    def SetContainer(self, option: PDM.CaeCloneManager.CloneOption, container: str) -> None:
        """[Obsolete("Deprecated in NX10.0.0.  Use NXOpen.PDM.PartOperationCopyBuilder instead.")"""
        ...
    def CommitClone(self) -> None:
        """[Obsolete("Deprecated in NX10.0.0.  Use NXOpen.PDM.PartOperationCopyBuilder instead.")"""
        ...


    class CloneOption(enum.Enum):
        None = -1
        Sim = 0
        Fem = 1
        Ideal = 2
        Master = 3
    

class AttributeGroupReviseBuilder(Builder):
    def __init__(self) -> None: ...
    def GetRevisedAttributeGroups(self) -> typing.List[PDM.AttributeGroup]:
        ...
    def GetOperationErrors(self) -> PDM.OperationErrors:
        ...
    def GetOperationFailures(self) -> ErrorList:
        ...
    def GetLogicalObjects(self) -> typing.List[PDM.LogicalObject]:
        ...


    class SaveAsActionType(enum.Enum):
        NewRevision = 0
        NewAttributeGroup = 1
    

class AttributeGroupDescriptionCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int:
        ...
    def ToArray(self) -> typing.List[PDM.AttributeGroupDescription]:
        ...
    def __init__(self, owner: PDM.PdmSession) -> None: ...
    def __init__(self) -> None: ...
    def FindObject(self, journalIdentifier: str) -> PDM.AttributeGroupDescription:
        ...
    def Tag(self) -> Tag: ...



class AttributeGroupDescription(NXObject):
    def __init__(self) -> None: ...
    DisplayName: str
    MaximumNumberOfAttributeGroupsAllowed: int
    MinimumNumberOfAttributeGroupsAllowed: int


class AttributeGroupCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int:
        ...
    def ToArray(self) -> typing.List[PDM.AttributeGroup]:
        ...
    def __init__(self, owner: CollaborativeDesign) -> None: ...
    def __init__(self) -> None: ...
    def FindObject(self, journalIdentifier: str) -> PDM.AttributeGroup:
        ...
    def Tag(self) -> Tag: ...



class AttributeGroup(NXObject):
    def __init__(self) -> None: ...
    def GetReferencingAttributeGroupOwners(self) -> typing.List[PDM.IAttributeGroupOwner]:
        ...
    def DetachAttributeGroup(self, attributeGroupOwner: PDM.IAttributeGroupOwner) -> None:
        ...
    def Create(self, attributeGroupDescription: PDM.AttributeGroupDescription) -> PDM.AttributeGroup:
        ...
    def CreateAttributeGroupReviseBuilder(self, attributeGroups: typing.List[PDM.AttributeGroup]) -> PDM.AttributeGroupReviseBuilder:
        ...
    def GetAttributeGroups(self) -> typing.List[PDM.AttributeGroup]:
        ...
    def GetAttributeGroupDescriptions(self) -> typing.List[PDM.AttributeGroupDescription]:
        ...
    def CreateAttributeGroupReviseBuilder(self, attributeGroups: typing.List[PDM.AttributeGroup], keepOriginal: bool, saveAsActionType: PDM.AttributeGroupReviseBuilder.SaveAsActionType) -> PDM.AttributeGroupReviseBuilder:
        ...
    DisplayName: str


class AssyCloneCompDisp(NXObject):
    def __init__(self) -> None: ...


class AlternateIdManager(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...
    def SetContext(self, context: str) -> None:
        ...
    def GetContext(self) -> str:
        ...
    def GetAllContexts(self) -> str:
        ...
    def SetIdType(self, idType: str) -> None:
        ...
    def GetIdType(self) -> str:
        ...
    def GetAllIdTypes(self, context: str) -> str:
        ...
    def SetAlternateItemId(self, alternateItemId: str) -> None:
        ...
    def AssignAlternateId(self, alternateItemId: str, alternateRevId: str) -> None:
        ...
    def GetAlternateItemId(self) -> str:
        ...
    def SetAlternateRevId(self, alternateRevId: str) -> None:
        ...
    def AssignAlternateRevId(self) -> str:
        ...
    def GetAlternateRevId(self) -> str:
        ...
    def SetAlternateName(self, alternateName: str) -> None:
        ...
    def GetAlternateName(self) -> str:
        ...
    def SetAlternateDescription(self, alternateDescription: str) -> None:
        ...
    def GetAlternateDescription(self) -> str:
        ...
    def SetAlternateIdAsDefaultIndentifier(self, alternateIdAsDefaultIndentifier: bool) -> None:
        ...
    def GetAlternateIdAsDefaultIndentifier(self) -> bool:
        ...
    def SetAlternateIdInformation(self, context: str, idType: str, alternateItemId: str, alternateRevId: str, alternateName: str, alternateDescription: str, alternateIdAsDefaultIndentifier: bool) -> None:
        ...
    def CreateAlternateIdInformation(self) -> None:
        ...
    def AssignAlternateIds(self, context: str, idType: str) -> PDM.AlternateIdManager.AlternateIdsData:
        ...
    def AssignAlternateRevision(self) -> PDM.AlternateIdManager.AssignAlternateRevData:
        ...


    class AlternateIdManagerAssignAlternateRevData():
        AlternateRevId: str
        Modifiable: bool
        def ToString(self) -> str:
            ...
        def __init__(self, AlternateRevId: str, Modifiable: bool) -> None: ...
    

    class AlternateIdManagerAlternateIdsData():
        AlternateItemId: str
        AlternateRevId: str
        AlternateName: str
        AlternateDescription: str
        Modifiable: bool
        def ToString(self) -> str:
            ...
    

    class AlternateIdManager_AssignAlternateRevData():
        alternate_rev_id: int
        modifiable: bool
    

    class AlternateIdManager_AlternateIdsData():
        alternate_item_id: int
        alternate_rev_id: int
        alternate_name: int
        alternate_description: int
        modifiable: bool
    

