from ...NXOpen import *
from ..DiagrammingLibraryAuthor import *

import typing
import enum

class SymbolSaveBuilder(Builder):
    def __init__(self) -> None: ...
    def GetDescription(self) -> str:
        ...
    def SetDescription(self, text: str) -> None:
        ...
    FolderPath: str
    Name: str


class SymbolPortBuilder(Builder):
    def __init__(self) -> None: ...
    def GetPortObject(self) -> DiagrammingLibraryAuthor.AttributeHolder:
        ...
    def SetLocation(self, portLocation: Point2d) -> None:
        ...
    def GetLocation(self) -> Point2d:
        ...
    def SetConnectionDirection(self, connectionDirection: Point2d) -> None:
        ...
    def GetConnectionDirection(self) -> Point2d:
        ...
    def SetPortID(self, portID: str) -> None:
        ...
    def GetPortID(self) -> str:
        ...
    def SetDirection(self, portDirection: str) -> None:
        ...
    def GetDirection(self) -> str:
        ...


class SymbolDesignerManager(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def GetSymbolDesignerManager(self, owner: Session) -> DiagrammingLibraryAuthor.SymbolDesignerManager:
        ...
    def CreateSymbolPart(self, symbolName: str) -> Part:
        ...
    def OpenSymbolPart(self, partSpec: str) -> Part:
        ...
    def CreateSymbolSaveBuilder(self, part: Part) -> DiagrammingLibraryAuthor.SymbolSaveBuilder:
        ...
    def CreateSymbolPortBuilder(self, part: Part, portID: str) -> DiagrammingLibraryAuthor.SymbolPortBuilder:
        ...
    def CreateSymbolBuilder(self, part: Part) -> DiagrammingLibraryAuthor.SymbolBuilder:
        ...
    def Tag(self) -> Tag: ...



class SymbolBuilder(Builder):
    def __init__(self) -> None: ...
    AnchorPoint: Point2d
    TagLocation: Point2d


class Symbol3DBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool:
        ...
    PortMappingData: ITableEditorDataProvider


class Symbol2DBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def CreateFromSymbol(self, symbolId: str) -> None:
        ...
    def Validate(self) -> bool:
        ...
    AnchorPoint: Point2d
    DraftingSymbol: Tooling.SelectReuseLibraryItemBuilder
    EnableScale: bool
    Image: Gateway.ImageCaptureBuilder
    IsInline: bool
    PortData: DiagrammingLibraryAuthor.PortDataBuilder
    PrefixLetters: str
    TagLocation: Point2d


class PortDataBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def GetPortObjects(self, portObjects: typing.List[DiagrammingLibraryAuthor.AttributeHolder]) -> None:
        ...
    def GetPointLocation(self, portObject: DiagrammingLibraryAuthor.AttributeHolder) -> Point2d:
        ...
    def SetPointLocation(self, portObject: DiagrammingLibraryAuthor.AttributeHolder, portLocation: Point2d) -> None:
        ...
    def GetConnectionDirection(self, portObject: DiagrammingLibraryAuthor.AttributeHolder) -> Point2d:
        ...
    def SetConnectionDirection(self, portObject: DiagrammingLibraryAuthor.AttributeHolder, connectionDirection: Point2d) -> None:
        ...
    def CreatePort(self) -> DiagrammingLibraryAuthor.AttributeHolder:
        ...
    def DeletePort(self, portObject: DiagrammingLibraryAuthor.AttributeHolder) -> None:
        ...
    def Validate(self) -> bool:
        ...
    NozzleBottom: bool
    NozzleLeft: bool
    NozzleRight: bool
    NozzleTop: bool


class PipeStockBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def SelectFolder(self, classId: str) -> None:
        ...
    def SelectPipeStock(self, symbolId: str) -> None:
        ...
    def GetPipeStockObjects(self, pipeStockObjects: typing.List[DiagrammingLibraryAuthor.AttributeHolder]) -> None:
        ...
    def CreatePipeStock(self, instanceId: str, partId: str, partName: str, numberName: str) -> DiagrammingLibraryAuthor.AttributeHolder:
        ...
    def DeletePipeStock(self, pipeStockObject: DiagrammingLibraryAuthor.AttributeHolder) -> None:
        ...
    def Validate(self) -> bool:
        ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class LineTypeBuilderList(TaggedObject):
    def __init__(self) -> None: ...
    def Append(self, objects: typing.List[DiagrammingLibraryAuthor.LineTypeBuilder]) -> None:
        ...
    def Append(self, object: DiagrammingLibraryAuthor.LineTypeBuilder) -> None:
        ...
    def ClearIndex(self, deleteIdx: int) -> None:
        ...
    def FindIndex(self, obj: DiagrammingLibraryAuthor.LineTypeBuilder) -> int:
        ...
    def FindItem(self, index: int) -> DiagrammingLibraryAuthor.LineTypeBuilder:
        ...
    def Erase(self, index: int) -> None:
        ...
    def Erase(self, index: int, deleteOption: ObjectList.DeleteOption) -> None:
        ...
    def Erase(self, obj: DiagrammingLibraryAuthor.LineTypeBuilder) -> None:
        ...
    def Erase(self, obj: DiagrammingLibraryAuthor.LineTypeBuilder, deleteOption: ObjectList.DeleteOption) -> None:
        ...
    def Clear(self) -> None:
        ...
    def Clear(self, deleteOption: ObjectList.DeleteOption) -> None:
        ...
    def GetContents(self) -> typing.List[DiagrammingLibraryAuthor.LineTypeBuilder]:
        ...
    def SetContents(self, objects: typing.List[DiagrammingLibraryAuthor.LineTypeBuilder]) -> None:
        ...
    def Swap(self, index1: int, index2: int) -> None:
        ...
    def Swap(self, object1: DiagrammingLibraryAuthor.LineTypeBuilder, object2: DiagrammingLibraryAuthor.LineTypeBuilder) -> None:
        ...
    def Insert(self, location: int, object: DiagrammingLibraryAuthor.LineTypeBuilder) -> None:
        ...
    def MoveToTop(self, index: int) -> None:
        ...
    def MoveToBottom(self, index: int) -> None:
        ...
    Length: int


class LineTypeBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool:
        ...
    LineColor: NXColor
    LineFont: DisplayableObject.ObjectFont
    LineTypeName: str
    LineTypePriority: int
    LineWidth: DisplayableObject.ObjectWidth
    ObjectId: str


class AttributeHolder(NXObject):
    def __init__(self) -> None: ...


