from ....NXOpen import *
from ...SIM import *
from ..PostConfigurator import *

import typing
import enum

class UdeParameterBuilderList(TaggedObject):
    def __init__(self) -> None: ...
    def Append(self, objects: typing.List[SIM.PostConfigurator.UdeParameterBuilder]) -> None:
        ...
    def Append(self, object: SIM.PostConfigurator.UdeParameterBuilder) -> None:
        ...
    def ClearIndex(self, deleteIdx: int) -> None:
        ...
    def FindIndex(self, obj: SIM.PostConfigurator.UdeParameterBuilder) -> int:
        ...
    def FindItem(self, index: int) -> SIM.PostConfigurator.UdeParameterBuilder:
        ...
    def Erase(self, index: int) -> None:
        ...
    def Erase(self, index: int, deleteOption: ObjectList.DeleteOption) -> None:
        ...
    def Erase(self, obj: SIM.PostConfigurator.UdeParameterBuilder) -> None:
        ...
    def Erase(self, obj: SIM.PostConfigurator.UdeParameterBuilder, deleteOption: ObjectList.DeleteOption) -> None:
        ...
    def Clear(self) -> None:
        ...
    def Clear(self, deleteOption: ObjectList.DeleteOption) -> None:
        ...
    def GetContents(self) -> typing.List[SIM.PostConfigurator.UdeParameterBuilder]:
        ...
    def SetContents(self, objects: typing.List[SIM.PostConfigurator.UdeParameterBuilder]) -> None:
        ...
    def Swap(self, index1: int, index2: int) -> None:
        ...
    def Swap(self, object1: SIM.PostConfigurator.UdeParameterBuilder, object2: SIM.PostConfigurator.UdeParameterBuilder) -> None:
        ...
    def Insert(self, location: int, object: SIM.PostConfigurator.UdeParameterBuilder) -> None:
        ...
    def MoveToTop(self, index: int) -> None:
        ...
    def MoveToBottom(self, index: int) -> None:
        ...
    Length: int


class UdeParameterBuilder(Builder):
    def __init__(self) -> None: ...
    def GetEnumerationItems(self) -> str:
        ...
    def SetEnumerationItems(self, enumerationItems: str) -> None:
        ...
    def SetGroup(self, parentBuilder: SIM.PostConfigurator.UdeParameterBuilder) -> None:
        ...
    DoubleDefaultValue: float
    EnumerationDefaultValue: str
    GroupState: SIM.PostConfigurator.UdeParameterBuilder.GroupStateType
    IntegerDefaultValue: int
    ItemType: SIM.PostConfigurator.UdeParameterBuilder.Type
    ParameterID: str
    ParameterStatus: SIM.PostConfigurator.UdeParameterBuilder.ParameterStatusType
    StringDefaultValue: str
    ToggleDefaultValue: bool
    UILabel: str


    class Type(enum.Enum):
        Group = 0
        Double = 1
        Integer = 2
        String = 3
        Boolean = 4
        Enumeration = 5
        Vector = 6
        Point = 7
        Bitmap = 8
    

    class ParameterStatusType(enum.Enum):
        None = 0
        On = 1
        Off = 2
    

    class GroupStateType(enum.Enum):
        Open = 0
        Closed = 1
        End = 2
    

class UdeEditorBuilder(Builder):
    def __init__(self) -> None: ...
    def GetUdeBuilder(self, eventHandlerID: str) -> SIM.PostConfigurator.UdeBuilder:
        ...
    def AddNewEvent(self) -> SIM.PostConfigurator.UdeBuilder:
        ...
    def DuplicateEvent(self, udeBuilder: SIM.PostConfigurator.UdeBuilder) -> SIM.PostConfigurator.UdeBuilder:
        ...
    def RemoveEvent(self, udeBuilder: SIM.PostConfigurator.UdeBuilder) -> None:
        ...
    def ListEvent(self, udeBuilder: SIM.PostConfigurator.UdeBuilder) -> None:
        ...
    UdeBuilderList: SIM.PostConfigurator.UdeBuilderList


class UdeBuilderList(TaggedObject):
    def __init__(self) -> None: ...
    def Append(self, objects: typing.List[SIM.PostConfigurator.UdeBuilder]) -> None:
        ...
    def Append(self, object: SIM.PostConfigurator.UdeBuilder) -> None:
        ...
    def ClearIndex(self, deleteIdx: int) -> None:
        ...
    def FindIndex(self, obj: SIM.PostConfigurator.UdeBuilder) -> int:
        ...
    def FindItem(self, index: int) -> SIM.PostConfigurator.UdeBuilder:
        ...
    def Erase(self, index: int) -> None:
        ...
    def Erase(self, index: int, deleteOption: ObjectList.DeleteOption) -> None:
        ...
    def Erase(self, obj: SIM.PostConfigurator.UdeBuilder) -> None:
        ...
    def Erase(self, obj: SIM.PostConfigurator.UdeBuilder, deleteOption: ObjectList.DeleteOption) -> None:
        ...
    def Clear(self) -> None:
        ...
    def Clear(self, deleteOption: ObjectList.DeleteOption) -> None:
        ...
    def GetContents(self) -> typing.List[SIM.PostConfigurator.UdeBuilder]:
        ...
    def SetContents(self, objects: typing.List[SIM.PostConfigurator.UdeBuilder]) -> None:
        ...
    def Swap(self, index1: int, index2: int) -> None:
        ...
    def Swap(self, object1: SIM.PostConfigurator.UdeBuilder, object2: SIM.PostConfigurator.UdeBuilder) -> None:
        ...
    def Insert(self, location: int, object: SIM.PostConfigurator.UdeBuilder) -> None:
        ...
    def MoveToTop(self, index: int) -> None:
        ...
    def MoveToBottom(self, index: int) -> None:
        ...
    Length: int


class UdeBuilder(Builder):
    def __init__(self) -> None: ...
    def AddItem(self, itemBuilder: SIM.PostConfigurator.UdeParameterBuilder) -> None:
        ...
    def DeleteItem(self, itemBuilder: SIM.PostConfigurator.UdeParameterBuilder) -> None:
        ...
    def DeleteItems(self) -> None:
        ...
    def GetUdeParameterBuilder(self, parameterID: str) -> SIM.PostConfigurator.UdeParameterBuilder:
        ...
    def RenameParameterID(self, itemBuilder: SIM.PostConfigurator.UdeParameterBuilder, oldParameterID: str, newParameterID: str) -> None:
        ...
    EventCategoryDrilling: bool
    EventCategoryMilling: bool
    EventCategoryTurning: bool
    EventCategoryWireEDM: bool
    EventDescription: SIM.PostConfigurator.UdeBuilder.EventDescriptionType
    EventHelpDescription: str
    EventHelpLocation: str
    EventID: str
    EventName: str
    PostEvent: str
    UdeParameterList: SIM.PostConfigurator.UdeParameterBuilderList


    class EventDescriptionType(enum.Enum):
        None = 0
        Specify = 1
    

class PostConfiguratorManager(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def CreateCreationPostBuilder(self) -> SIM.PostConfigurator.CreationPostBuilder:
        ...
    def CreatePostConfiguratorBuilder(self, postProcessorFilename: str) -> SIM.PostConfigurator.PostConfiguratorBuilder:
        ...
    def CreateUdeBuilder(self) -> SIM.PostConfigurator.UdeBuilder:
        ...
    def CreateUdeParameterBuilder(self) -> SIM.PostConfigurator.UdeParameterBuilder:
        ...
    def Tag(self) -> Tag: ...



class PostConfiguratorBuilder(Builder):
    def __init__(self) -> None: ...
    def Reset(self) -> None:
        ...
    def ShowChanges(self) -> None:
        ...
    def EncryptPostConfiguratorFiles(self, soldToID: str, expirationDate: str) -> None:
        ...
    def SaveAs(self, postprocessorName: str, outputDirectory: str) -> None:
        ...
    def PostProcess(self, objects: typing.List[CAM.CAMObject], outputFilename: str, showOutputToListingWindow: bool) -> None:
        ...
    DateValue: DateBuilder
    LayerManagerBuilder: SIM.PostConfigurator.LayerManagerBuilder
    UdeEditorBuilder: SIM.PostConfigurator.UdeEditorBuilder


class LayerManagerBuilder(Builder):
    def __init__(self) -> None: ...


class CreationPostBuilder(Builder):
    def __init__(self) -> None: ...
    def GetControllerNames(self) -> str:
        ...
    def GetManufacturerNames(self) -> str:
        ...
    def GetMachineNames(self) -> str:
        ...
    ControllerName: str
    MachineName: str
    ManufacturerName: str
    PostprocessorName: str
    PostprocessorOutputDirectory: str


