from ...NXOpen import *
from ..RegionRecognition import *

import typing
import enum

class RegionFinderBuilder(Builder):
    def __init__(self) -> None: ...
    def SetOriginRegion(self, objects: typing.List[TaggedObject]) -> bool:
        ...
    def PerformSearch(self) -> typing.List[TaggedObject]:
        ...
    def SetSimilarFlag(self, similarFlag: int) -> bool:
        ...
    def SetSearchMethod(self, searchMethod: int) -> None:
        ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class Manager(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def GetManager(self, owner: Session) -> RegionRecognition.Manager:
        ...
    def CreateRegionFinderBuilder(self, part: NXObject) -> RegionRecognition.RegionFinderBuilder:
        ...
    def Tag(self) -> Tag: ...



