from ..NXOpenUI import *

import typing
import enum

class NXInputBox(System.Object):
    def GetInputString(self, prompt: str) -> str:
        ...
    def GetInputString(self, prompt: str, caption: str) -> str:
        ...
    def GetInputString(self, prompt: str, caption: str, initialText: str) -> str:
        ...
    def GetInputNumber(self, prompt: str) -> float:
        ...
    def GetInputNumber(self, prompt: str, caption: str) -> float:
        ...
    def GetInputNumber(self, prompt: str, caption: str, initialText: str) -> float:
        ...
    def GetInputNumber(self, prompt: str, caption: str, initialNumber: float) -> float:
        ...
    def ParseInputNumber(self, prompt: str, caption: str, initialText: str) -> bool:
        ...
    def ParseInputNumber(self, prompt: str, caption: str, initialNumber: float) -> bool:
        ...
    def __init__(self) -> None: ...


class FormUtilities(System.Object):
    def GetNXIcon(self) -> None:
        ...
    def SetApplicationIcon(self) -> None:
        ...
    def GetDefaultParentWindowHandle(self) -> int:
        ...
    def ReparentForm(self) -> None:
        ...
    def __init__(self) -> None: ...


