from ...NXOpen import *
from ..OpenXml import *

import typing
import enum

class TextDocumentData(OpenXml.DocumentData):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...
    def GetContent(self) -> str:
        ...
    def SetContent(self, content: str) -> None:
        ...


class TableDocumentData(OpenXml.DocumentData):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...
    def GetColumnCount(self) -> int:
        ...
    def GetRowCount(self) -> int:
        ...
    def GetCaption(self, position: OpenXml.TableDocumentData.CaptionPosition) -> str:
        ...
    def SetCaption(self, position: OpenXml.TableDocumentData.CaptionPosition, caption: str) -> None:
        ...
    def GetColumnWidths(self) -> float:
        ...
    def SetColumnWidths(self, widths: float) -> None:
        ...
    def GetRowHeigths(self) -> float:
        ...
    def SetRowHeigths(self, heigths: float) -> None:
        ...
    def AddCellData(self, grids: int) -> OpenXml.TableCellData:
        ...
    def GetCellsCount(self) -> int:
        ...
    def GetNthCell(self, index: int) -> OpenXml.TableCellData:
        ...


    class CaptionPosition(enum.Enum):
        Above = 0
        Bellow = 1
    

class TableCellData(OpenXml.DocumentData):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...
    def GetGridsId(self) -> int:
        ...
    def AddText(self, textContent: str) -> OpenXml.TextDocumentData:
        ...
    def AddImageGroup(self) -> OpenXml.ImageGroupDocumentData:
        ...
    def GetContentCount(self) -> int:
        ...
    def GetNthContent(self, index: int) -> OpenXml.DocumentData:
        ...
    def DeleteNthContent(self, index: int) -> None:
        ...
    def ClearContents(self) -> None:
        ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class ImageGroupDocumentData(OpenXml.DocumentData):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...
    def AddImage(self, fileName: str, caption: str) -> OpenXml.ImageDocumentData:
        ...
    def GetImagesCount(self) -> int:
        ...
    def GetNthImage(self, index: int) -> OpenXml.ImageDocumentData:
        ...
    def DeleteNthImage(self, index: int) -> None:
        ...
    def DeleteAllImages(self) -> None:
        ...


class ImageDocumentData(OpenXml.DocumentData):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...
    def GetFileName(self) -> str:
        ...
    def SetFileName(self, fileName: str) -> None:
        ...
    def GetCaption(self, position: OpenXml.ImageDocumentData.CaptionPosition) -> str:
        ...
    def SetCaption(self, position: OpenXml.ImageDocumentData.CaptionPosition, caption: str) -> None:
        ...


    class CaptionPosition(enum.Enum):
        Above = 0
        Bellow = 1
    

class DocumentDataGroup(OpenXml.DocumentData):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...
    def AddText(self, textContent: str) -> OpenXml.TextDocumentData:
        ...
    def AddImageGroup(self) -> OpenXml.ImageGroupDocumentData:
        ...
    def AddTable(self, columnCount: int, rowCount: int) -> OpenXml.TableDocumentData:
        ...
    def GetDataCount(self) -> int:
        ...
    def GetNthData(self, index: int) -> OpenXml.DocumentData:
        ...
    def DeleteNthData(self, index: int) -> None:
        ...
    def DeleteAllData(self) -> None:
        ...


class DocumentData(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...
    def GetDataType(self) -> OpenXml.DocumentData.Type:
        ...


    class Type(enum.Enum):
        Base = 0
        Text = 1
        Table = 2
        TableCell = 3
        Image = 4
        ImageGroup = 5
        Group = 6
    

