from ...NXOpen import *
from ..ModlUtils import *

import typing
import enum

class SelectObjectDimListItemList(TaggedObject):
    def __init__(self) -> None: ...
    def Append(self, objects: typing.List[ModlUtils.SelectObjectDimListItem]) -> None:
        ...
    def Append(self, object: ModlUtils.SelectObjectDimListItem) -> None:
        ...
    def ClearIndex(self, deleteIdx: int) -> None:
        ...
    def FindIndex(self, obj: ModlUtils.SelectObjectDimListItem) -> int:
        ...
    def FindItem(self, index: int) -> ModlUtils.SelectObjectDimListItem:
        ...
    def Erase(self, index: int) -> None:
        ...
    def Erase(self, index: int, deleteOption: ObjectList.DeleteOption) -> None:
        ...
    def Erase(self, obj: ModlUtils.SelectObjectDimListItem) -> None:
        ...
    def Erase(self, obj: ModlUtils.SelectObjectDimListItem, deleteOption: ObjectList.DeleteOption) -> None:
        ...
    def Clear(self) -> None:
        ...
    def Clear(self, deleteOption: ObjectList.DeleteOption) -> None:
        ...
    def GetContents(self) -> typing.List[ModlUtils.SelectObjectDimListItem]:
        ...
    def SetContents(self, objects: typing.List[ModlUtils.SelectObjectDimListItem]) -> None:
        ...
    def Swap(self, index1: int, index2: int) -> None:
        ...
    def Swap(self, object1: ModlUtils.SelectObjectDimListItem, object2: ModlUtils.SelectObjectDimListItem) -> None:
        ...
    def Insert(self, location: int, object: ModlUtils.SelectObjectDimListItem) -> None:
        ...
    def MoveToTop(self, index: int) -> None:
        ...
    def MoveToBottom(self, index: int) -> None:
        ...
    Length: int


class SelectObjectDimListItemBuilderList(TaggedObject):
    def __init__(self) -> None: ...
    def Append(self, objects: typing.List[ModlUtils.SelectObjectDimListItemBuilder]) -> None:
        ...
    def Append(self, object: ModlUtils.SelectObjectDimListItemBuilder) -> None:
        ...
    def ClearIndex(self, deleteIdx: int) -> None:
        ...
    def FindIndex(self, obj: ModlUtils.SelectObjectDimListItemBuilder) -> int:
        ...
    def FindItem(self, index: int) -> ModlUtils.SelectObjectDimListItemBuilder:
        ...
    def Erase(self, index: int) -> None:
        ...
    def Erase(self, index: int, deleteOption: ObjectList.DeleteOption) -> None:
        ...
    def Erase(self, obj: ModlUtils.SelectObjectDimListItemBuilder) -> None:
        ...
    def Erase(self, obj: ModlUtils.SelectObjectDimListItemBuilder, deleteOption: ObjectList.DeleteOption) -> None:
        ...
    def Clear(self) -> None:
        ...
    def Clear(self, deleteOption: ObjectList.DeleteOption) -> None:
        ...
    def GetContents(self) -> typing.List[ModlUtils.SelectObjectDimListItemBuilder]:
        ...
    def SetContents(self, objects: typing.List[ModlUtils.SelectObjectDimListItemBuilder]) -> None:
        ...
    def Swap(self, index1: int, index2: int) -> None:
        ...
    def Swap(self, object1: ModlUtils.SelectObjectDimListItemBuilder, object2: ModlUtils.SelectObjectDimListItemBuilder) -> None:
        ...
    def Insert(self, location: int, object: ModlUtils.SelectObjectDimListItemBuilder) -> None:
        ...
    def MoveToTop(self, index: int) -> None:
        ...
    def MoveToBottom(self, index: int) -> None:
        ...
    Length: int


class SelectObjectDimListItemBuilder(Builder):
    def __init__(self) -> None: ...
    Dimension: Expression
    Selection: SelectDisplayableObjectList


class SelectObjectDimListItem(Builder):
    def __init__(self) -> None: ...
    Dimension: Expression
    Selection: SelectDisplayableObjectList


class SelectObjectDimListBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def CreateSelectObjectDimListItemBuilder(self) -> ModlUtils.SelectObjectDimListItemBuilder:
        ...
    def Validate(self) -> bool:
        ...
    List: ModlUtils.SelectObjectDimListItemBuilderList


class SelectObjectDimList(TaggedObject):
    def __init__(self) -> None: ...
    def CreateSelectObjectDimListItem(self) -> ModlUtils.SelectObjectDimListItem:
        ...
    def Validate(self) -> bool:
        ...
    List: ModlUtils.SelectObjectDimListItemList


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class EquationEditorBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool:
        ...
    EquationString: str


