from ...NXOpen import *
from ..PartFamily import *

import typing
import enum

class TemplateManager(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...
    def GetSelectableAttributes(self, attrType: PartFamily.FamilyAttribute.AttrType) -> str:
        ...
    def DeletePartFamilyAttribute(self, partFamilyAttribute: PartFamily.FamilyAttribute) -> None:
        ...
    def GetChosenAttributes(self) -> typing.List[PartFamily.FamilyAttribute]:
        ...
    def AddToChosenAttributes(self, attrsToAdd: str, attrsTypes: typing.List[PartFamily.FamilyAttribute.AttrType], indexAddAt: int) -> None:
        ...
    def AddAssertedMassToChosenAttributes(self, attrToAdd: str, indexAddAt: int) -> None:
        ...
    def MoveDownAttributes(self, moveDownAttrs: typing.List[PartFamily.FamilyAttribute], moveDownCount: int) -> int:
        ...
    def MoveUpAttributes(self, moveUpAttrs: typing.List[PartFamily.FamilyAttribute], moveUpCount: int) -> int:
        ...
    def CutAttributes(self, cutAttrs: typing.List[PartFamily.FamilyAttribute]) -> None:
        ...
    def PasteAttributes(self, pasteAfter: PartFamily.FamilyAttribute) -> None:
        ...
    def CreatePartFamily(self) -> PartFamily.Template:
        ...
    def EditPartFamily(self) -> None:
        ...
    def DeletePartFamily(self) -> None:
        ...
    def EstablishFamilyInstance(self, memberName: str) -> str:
        ...
    def GetInstanceDefinition(self, familyMemberDefnName: str) -> PartFamily.InstanceDefinition:
        ...
    def GetInstanceDefinitionUsingMemberIdentifier(self, familyMemberIdentifier: PartFamily.MemberIdentifier) -> PartFamily.InstanceDefinition:
        ...
    def AddInstanceDefinition(self, familyMemberDefnName: str, previousFamilyMemberDefn: PartFamily.InstanceDefinition, otherNameEntry: str) -> PartFamily.InstanceDefinition:
        ...
    def AddInstanceDefinitionUsingMemberIdentifier(self, familyMemberIdentifier: PartFamily.MemberIdentifier, previousFamilyMemberDefn: PartFamily.InstanceDefinition, otherNameEntry: str) -> PartFamily.InstanceDefinition:
        ...
    def DeleteInstanceDefinition(self, familyMemberDefinition: PartFamily.InstanceDefinition) -> None:
        ...
    def ReorderInstanceDefinition(self, familyMemberDefinition: PartFamily.InstanceDefinition, previousFamilyMemberDefn: PartFamily.InstanceDefinition) -> None:
        ...
    def SavePartFamily(self) -> None:
        ...
    def GetPartFamilyAttribute(self, attrType: PartFamily.FamilyAttribute.AttrType, attrName: str) -> PartFamily.FamilyAttribute:
        ...
    def SaveFamilyAndCreateMembers(self, instDefsToCreate: typing.List[PartFamily.InstanceDefinition]) -> int:
        ...
    def SaveFamilyAndUpdateMembers(self, forceUpdate: bool, instDefsToUpdate: typing.List[PartFamily.InstanceDefinition]) -> int:
        ...
    def SaveFamilyAndFixOrphanMembers(self, forceUpdate: bool, instDefsToFix: typing.List[PartFamily.InstanceDefinition]) -> int:
        ...
    def SaveFamilyAndApplyValues(self, familyMemberDefinition: PartFamily.InstanceDefinition) -> int:
        ...
    def GetPartFamilyTemplate(self) -> PartFamily.Template:
        ...
    def AddOptionalCreationNonKeyAttrsToChosenAttrs(self, pasteAfter: PartFamily.FamilyAttribute) -> typing.List[PartFamily.FamilyAttribute]:
        ...
    def RefreshDefaultAttrs(self) -> None:
        ...
    def GetAllKeyAttrs(self) -> typing.List[PartFamily.FamilyAttribute]:
        ...
    def CreateMemberIdentifier(self, keyAttrs: typing.List[PartFamily.FamilyAttribute], attrValues: str, itemType: str) -> PartFamily.MemberIdentifier:
        ...
    def GetInfoMessages(self) -> str:
        ...
    Importable: bool
    SaveDirectory: str


class Template(NXObject):
    def __init__(self) -> None: ...
    def GetAttributes(self) -> typing.List[PartFamily.FamilyAttribute]:
        ...
    def GetValidAttributeValues(self, attr: PartFamily.FamilyAttribute) -> str:
        ...
    def GetMembers(self, members: str) -> None:
        ...
    def IsValidMemberName(self, memberName: str) -> bool:
        ...
    TemplateName: str
    Version: int


class MemberIdentifier(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...


class InstanceSelectionCriteria(TaggedObject):
    def __init__(self) -> None: ...
    def GetCriteriaStrings(self, criteriaStringArray: str) -> None:
        ...
    def SetPartFamilyInstanceSelectionCriteria(self, attributes: typing.List[PartFamily.FamilyAttribute], criteriaStringArray: str) -> None:
        ...
    def SetPartFamilyInstanceSelectionCriteria(self, memberName: str) -> None:
        ...
    def IsValidPartFamilyInstanceSelectionCriteria(self) -> bool:
        ...
    Family: PartFamily.Template
    Instance: PartFamily.Instance


class InstanceDefinition(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None:
        ...
    def SetValueOfAttribute(self, partFamAttr: PartFamily.FamilyAttribute, value: str) -> None:
        ...
    def GetValueOfAttribute(self, partFamAttr: PartFamily.FamilyAttribute) -> str:
        ...


class Instance(TaggedObject):
    def __init__(self) -> None: ...
    def IsOutOfDate(self) -> bool:
        ...
    Family: PartFamily.Template
    Version: int


class FamilyAttribute(NXObject):
    def __init__(self) -> None: ...
    IsOptional: bool
    IsRequired: bool
    Name: str
    Type: PartFamily.FamilyAttribute.AttrType
    Value: str
    Version: int


    class AttrType(enum.Enum):
        Text = 1
        Numeric = 2
        Integer = 3
        Double = 4
        String = 5
        Part = 6
        Name = 7
        Instance = 8
        Expression = 9
        Mirror = 10
        Density = 11
        Feature = 12
        Mass = 13
        Material = 14
        Undefined = 15
    

